import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../utils/txa_logger.dart';

class TxaLanguage extends ChangeNotifier {
  static final TxaLanguage _instance = TxaLanguage._internal();
  factory TxaLanguage() => _instance;
  TxaLanguage._internal();

  static String _currentLang = 'vi';
  static Function()? onLanguageChanged;
  static final Map<String, Map<String, String>> _dicts = {
    'vi': {
      'preparing': 'Đang chuẩn bị...',
      'logout': 'Đăng xuất',
      'app_name': 'DongMePhim',
      'ok': 'Đồng ý',
      'cancel': 'Hủy bỏ',
      'clear': 'Xóa',
      'check_update': 'Kiểm tra cập nhật',
      'downloading': 'Đang tải',
      'downloading_status': 'Đang tải: %p%% • %s% • ETA: %e%',
      'pending': 'Đang chờ',
      'paused': 'Đã tạm dừng',
      'notification_canceled': 'Đã hủy thông báo',
      'opening_external_browser': 'Đang mở trình duyệt ngoài...',
      'offline_no_downloads_title': 'Chưa có phim tải về',
      'offline_no_downloads_msg':
          'Bạn đang ngoại tuyến và chưa có phim nào được tải xuống để xem.',
      'login_required': 'Vui lòng đăng nhập để tiếp tục.',
      'account_banned_title': 'Tài khoản bị khóa',
      'exit_app': 'Thoát ứng dụng',
      'verify_email': 'Xác thực email',
      'verifying_email': 'Đang xác thực email...',
      'verify_success': 'Xác thực thành công',
      'verify_success_msg': 'Email của bạn đã được xác thực thành công.',
      'verify_failed': 'Xác thực thất bại',
      'verify_failed_msg':
          'Không thể xác thực email. Liên kết có thể đã hết hạn hoặc không hợp lệ.',
      'error': 'Lỗi',
      'success': 'Thành công',
      'permissions_required': 'Yêu cầu quyền truy cập',
      'camera_permission_denied': 'Quyền Truy Cập Camera Bị Từ Chối',
      'grant_camera_permission': 'Cấp quyền camera',
      'storage_permission_msg':
          'Ứng dụng cần quyền quản lý tệp để lưu nhật ký và tải ứng dụng.',
      'grant': 'Cấp quyền',
      'skip': 'Bỏ qua',
      'retry': 'Thử lại',
      'network_error': 'Không có kết nối mạng',
      'update_available': 'Có bản cập nhật mới',
      'update_now': 'Cập nhật ngay',
      'later': 'Để sau',
      'no_movies': 'Không tìm thấy phim nào',
      'error_loading_data': 'Không thể tải dữ liệu',
      'loading_data': 'Đang tải dữ liệu...',
      'error_search': 'Lỗi tìm kiếm',
      'no_changelog': 'Chưa có lịch sử cập nhật',
      'new_update_movies': 'Phim mới cập nhật',
      'hot_movies': 'Phim hot',
      'anime_cartoon': 'Anime & Hoạt hình',
      'series_movies': 'Phim bộ mới',
      'single_movies': 'Phim lẻ mới',
      'cartoon_movies': 'Hoạt hình mới',
      'tv_shows': 'TV Shows',
      'theater_movies': 'Phim chiếu rạp',
      'search': 'Tìm kiếm',
      'home': 'Trang chủ',
      'categories': 'Thể loại',
      'schedule': 'Lịch chiếu',
      'logs': 'Nhật ký',
      'clear_logs_confirm': 'Xóa toàn bộ nhật ký?',
      'clear_logs_msg': 'Hành động này sẽ xóa tất cả tệp log hiện có.',
      'no_logs_found': 'Không tìm thấy nhật ký nào.',
      'profile': 'Cá nhân',
      'app_premium': 'Mobile Premium',
      'connecting': 'Đang kết nối...',
      'retry_connection': 'Thử lại kết nối',
      'more': 'Thêm',
      'watch_now': 'Xem ngay',
      'watch_resume': 'Xem tiếp %ep%',
      'admin_scanning': 'Đang quét tập mới cho phim...',
      'admin_scan_success_added': 'Đã tìm thấy và cập nhật thêm %count% tập mới thành công!',
      'admin_scan_up_to_date': 'Phim đã được đồng bộ. Không có tập mới nào được tìm thấy.',
      'admin_scan_error': 'Lỗi quét tập mới: %error%',
      'admin_scan_btn': 'Quét tập mới',
      'admin_scanning_btn': 'Đang quét...',
      'add_favorite': 'Yêu thích',
      'favorite_added': 'Đã thêm vào danh sách yêu thích ❤️',
      'favorite_removed': 'Đã xóa khỏi danh sách yêu thích',
      'login_required_favorites': 'Vui lòng đăng nhập để lưu phim yêu thích.',
      'tv_add_favorite': 'Yêu thích',
      'trending_categories': 'Bạn đang quan tâm gì?',
      'see_all': 'Xem tất cả',
      'permission_storage_label': 'Quản lý tệp & Bộ nhớ',
      'permission_storage_desc':
          'Bắt buộc để tải xuống phim và lưu nhật ký ứng dụng.',
      'permission_notif_label': 'Thông báo đẩy',
      'permission_notif_desc':
          'Nhận thông báo khi có tập phim mới hoặc lịch chiếu.',
      'permission_install_label': 'Cài đặt ứng dụng',
      'permission_install_desc':
          'Bắt buộc để ứng dụng có thể tự động nâng cấp phiên bản mới.',
      'permission_nearby_devices_label': 'Thiết bị ở gần (Nearby)',
      'permission_nearby_devices_desc':
          'Bắt buộc để tìm kiếm và kết nối với các thiết bị Cast/TV trong mạng local.',
      'permission_bluetooth_label': 'Bluetooth (Dò thiết bị)',
      'permission_bluetooth_desc':
          'Cần thiết để phát hiện các thiết bị truyền tải không dây xung quanh.',
      'permission_nearby_devices_denied':
          'Quyền truy cập thiết bị ở gần bị từ chối. Không thể dò TV.',
      'screenshot_detected': 'Đã chụp màn hình',
      'share_screenshot': 'Chia sẻ ảnh chụp',
      'press_back_again': 'Nhấn lần nữa để thoát ứng dụng',
      'player_settings': 'Cài đặt trình phát',
      'language': 'Ngôn ngữ',
      'select_language': 'Chọn ngôn ngữ',
      'vi_lang': 'Tiếng Việt',
      'en_lang': 'Tiếng Anh',
      'loading_progress': 'Đang chuẩn bị dữ liệu...',
      'splash_check_permissions': 'Kiểm tra quyền truy cập...',
      'splash_init_language': 'Khởi tạo ngôn ngữ...',
      'splash_config_system': 'Cấu hình hệ thống...',
      'splash_init_download': 'Khởi tạo trình tải xuống...',
      'splash_ios_no_access': 'Bạn chưa có quyền truy cập ứng dụng này.',
      'splash_init_failed': 'Khởi tạo thất bại',
      'splash_error_title': 'Oops! Đã có lỗi xảy ra',
      'splash_error_copy': 'Copy Lỗi',
      'splash_error_copied': 'Đã copy mã lỗi!',
      'splash_browser_error': 'Không thể mở trình duyệt',
      'splash_get_access': 'Lấy quyền truy cập ứng dụng',
      'splash_safari_note':
          'Lưu ý: Bạn cần cài đặt Profile xác minh sau khi mở Safari.',
      'maintenance_title': 'Hệ thống đang bảo trì',
      'maintenance_msg':
          'Chúng tôi đang nâng cấp hệ thống để mang lại trải nghiệm tốt hơn. Vui lòng quay lại sau ít phút.',
      'check_permissions': 'Kiểm tra quyền truy cập',
      'please_grant_all': 'Vui lòng cấp các quyền bắt buộc để tiếp tục.',
      'go_to_settings': 'Vào cài đặt',
      'permissions_mandatory': 'Quyền bắt buộc',
      'permissions_optional': 'Quyền tùy chọn',
      'granted': 'Đã cấp',
      'denied': 'Chưa cấp',
      'continue': 'Tiếp tục',
      'permission_location_label': 'Vị trí',
      'permission_location_desc': 'Yêu cầu để kiểm tra tốc độ mạng chính xác.',
      'permission_nearby_label': 'Thiết bị ở gần',
      'permission_nearby_desc': 'Dùng để tìm và truyền video lên TV (Cast).',
      'speed_test_error':
          'Không thể bắt đầu kiểm tra tốc độ. Vui lòng cấp quyền vị trí hoặc thử lại sau.',
      'feature_dev': 'Tính năng đang phát triển',
      'feature_under_dev': 'Tính năng "%label" đang được phát triển',
      'coming_soon': 'Tính năng đang phát triển',
      'coming_soon_msg':
          'Tính năng này sẽ sớm ra mắt trong các bản cập nhật tới. Vui lòng quay lại sau nhé!',
      'earn_money': 'Giới thiệu kiếm tiền',
      'episodes': 'Tập phim',
      'episode': 'Tập',
      'loading_home': 'Đang tải trang chủ...',
      'loading_movie': 'Đang tải thông tin phim...',
      'all_movies_count': '%count% phim',
      'recommendation': 'Đề xuất',
      'no_episodes': 'Không có tập phim nào',
      'not_found_movie': 'Không tìm thấy phim',
      'select_server': 'Chọn Server',
      'related_parts': 'Chọn phần nào',
      'series_parts': 'Chọn phần nào',
      'actors': 'Diễn viên',
      'no_actors': 'Chưa cập nhật diễn viên',
      'download': 'Tải xuống',
      'download_label': 'Tốc độ tải xuống',
      'upload_label': 'Tốc độ tải lên',
      'share': 'Chia sẻ',
      'favorite_list': 'Yêu thích',
      'collapse': 'Thu gọn',
      'show_more': 'Xem thêm',
      'broadcast_msg':
          '%prefix% sẽ phát sóng vào %time%. Các bạn nhớ đón xem nhé 😙',
      'broadcast_final_msg':
          'Đừng bỏ lỡ %prefix% (Hồi kết) sẽ phát sóng vào %time% 🥹',
      'broadcast_suffix':
          'Phim sẽ phát sóng tập tiếp theo vào %time%. Các bạn nhớ đón xem nhé 😙',
      'final_ep': 'Tập cuối',
      'final_part': 'Hồi kết',
      'current_version': 'Phiên bản hiện tại: %version%',
      'update_history': 'Lịch sử cập nhật',
      'general_settings': 'Cài đặt chung',
      'app_settings': 'Cài đặt ứng dụng',
      'community_support': 'Cộng đồng & Hỗ trợ',
      'legal': 'Pháp lý',
      'clear_cache_msg':
          'Bạn có chắc chắn muốn xóa bộ nhớ tạm? Hành động này sẽ giải phóng dung lượng nhưng không ảnh hưởng đến dữ liệu đã lưu.',
      'session_expired': 'Phiên đăng nhập hết hạn',
      'load_error': 'Lỗi tải thông tin',
      'login_again_msg': 'Vui lòng đăng nhập lại để tiếp tục',
      'up_to_date': 'Bạn đang sử dụng phiên bản mới nhất (%version%)',
      'update_error': 'Lỗi kiểm tra cập nhật',
      'checking_update': 'Đang kiểm tra phiên bản mới...',
      'whats_new': 'Có gì mới:',
      'version_label': 'Phiên bản %version%',
      'volume': 'Âm lượng',
      'speed': 'Tốc độ',
      'skip_intro': 'Bỏ qua Intro',
      'auto_next_ep': 'Auto Next Tập Tiếp',
      'skip_outro_next': 'Bỏ qua Outro / Tập Tiếp',
      'prep_next_ep': 'Đang chuẩn bị tập tiếp theo...',
      'video_error': 'Lỗi tải video. Vui lòng thử lại!',
      'search_hint': 'Tìm phim, diễn viên...',
      'searching': 'Đang tìm kiếm...',
      'search_results': 'Kết quả (%count%)',
      'search_no_results': 'Không tìm thấy kết quả cho "%query"',
      'search_hot_title': '🔥 Được tìm nhiều nhất',
      'search_input_prompt': 'Nhập từ khóa để tìm phim',
      'clear_filter': 'Xóa lọc',
      'category_label': 'Thể loại: %name',
      'views_count': '%count lượt',
      'movie_series': 'Phim bộ',
      'movie_single': 'Phim lẻ',
      'year_label': 'Năm %year',
      'today': 'Hôm nay',
      'loading_schedule': 'Đang tải lịch chiếu...',
      'no_schedule_today': 'Hôm nay chưa có lịch chiếu',
      'no_schedule_date': 'Không có lịch chiếu vào %date',
      'unknown_episode': 'Tập ???',
      'watching': 'Đang xem',
      'my_list_long': 'Danh sách phim của tôi',
      'tv_login': 'Đăng nhập SmartTV',
      'fb_fanpage': 'Fanpage Facebook',
      'tg_channel': 'Kênh Telegram',
      'tg_support': 'Nhóm Telegram (Hỗ trợ)',
      'zalo_group': 'Nhóm Zalo',
      'terms_of_service': 'Điều khoản dịch vụ',
      'privacy_policy': 'Chính sách bảo mật',
      'forgot_password': 'Quên mật khẩu?',
      'exact_alarm_permission_denied': 'Thiếu quyền đặt báo thức.',
      'notification_permission_denied': 'Quyền thông báo bị từ chối.',
      'notification_scheduled': 'Đã đặt nhắc nhở 🔔',
      'notification_cancelled': 'Đã hủy nhắc nhở',
      'notification_time_passed': 'Thời gian chiếu đã trôi qua',
      'broadcast_reminder_title': 'Sắp công chiếu: %name%',
      'broadcast_reminder_body':
          '%movie% sẽ bắt đầu sau %minutes% phút nữa. Đừng bỏ lỡ nhé!',
      'view_movie_detail': 'Xem chi tiết',
      'bg_new_episode_title_simple': 'Tập mới: %n%',
      'broadcast_now_title': 'Bắt đầu công chiếu: %name%',
      'broadcast_now_body': 'Phim %movie% đang được công chiếu. Xem ngay thôi!',
      'download_fetching_playlist': 'Đang lấy thông tin...',
      'download_downloading_segments': 'Đang tải segment %c%/%t%...',
      'download_merging_video': 'Đang ghép video...',

      'save_changes': 'Lưu thay đổi',
      'not_open_link': 'Không thể mở liên kết',
      'close': 'Đóng',
      'cannot_download_update': 'Không thể tải bản cập nhật. Vui lòng thử lại!',
      'download_failed_network':
          'Tải thất bại: Lỗi kết nối mạng (Kiểm tra Wifi/4G) 🌐',
      'download_failed_server':
          'Tải thất bại: Lỗi máy chủ (Vui lòng thử lại sau) 🚫',
      'update_checking': 'Đang kiểm tra phiên bản mới...',
      'login_required_history': 'Vui lòng đăng nhập để xem lịch sử phim.',
      'error_unknown': 'Đã xảy ra lỗi không xác định',
      'resolver_error': 'Lỗi resolver: %error',
      'no_sources_found': 'Không tìm thấy nguồn phát hợp lệ cho tập này.',
      'all_sources_failed': 'Tất cả các nguồn phát đều thất bại.',
      'player_source_fallback':
          'Nguồn lỗi, đang thử nguồn %current%/%total%...',
      'TXA_PB1': 'Phim bộ mới',
      'TXA_PL1': 'Phim lẻ mới',
      'TXA_NEW1': 'Phim mới cập nhật',
      'TXA_HOT1': 'Phim hot',
      'TXA_HH1': 'Anime & Hoạt hình',
      'TXA_TV1': 'TV Shows',
      'TXA_CR1': 'Phim chiếu rạp',
      'TXA_LIST1': 'Danh sách phim',
      'player_brightness': 'Độ sáng',
      'player_audio': 'Âm thanh',
      'player_speed': 'Tốc độ phát',
      'loading_video': 'Đang tải video...',
      'player_lock': 'Khóa màn hình',
      'player_unlock': 'Mở khóa',
      'player_play': 'Phát',
      'player_pause': 'Tạm dừng',
      'player_close': 'Đóng phim',
      'player_show_clock': 'Đồng hồ',
      'player_clock_format': 'Định dạng giờ',
      'player_dnd_auto': 'Tự động "Không làm phiền"',
      'player_episodes': 'Danh sách tập',
      'player_gesture_hint': 'Vuốt để chỉnh độ sáng/âm lượng',
      'player_fast_forward_2x': 'Đang tua nhanh 2x',
      'player_seek_forward': 'Tua tới %count giây',
      'player_seek_backward': 'Tua lùi %count giây',
      'player_watermark': 'DongMePhim',
      'player_ratio': 'Tỷ lệ',
      'player_audio_track': 'Âm thanh',
      'player_seek_hint_short': 'Chạm đúp',
      'player_subtitle': 'Phụ đề',
      'player_system_control_blocked':
          'App đang điều khiển hệ thống, không thể chỉnh tay',
      'player_start_in': 'Bắt đầu sau',
      'prev_ep': 'Tập trước',
      'next_ep': 'Tập tiếp',
      'current_label': 'Hiện tại',
      'server_switch_hint': 'Chọn server để xem ở nguồn khác',
      'server_ep_unavailable_title': 'Tập phim không khả dụng',
      'server_ep_unavailable_msg':
          'Tập %ep chưa có trên server %server. Tự động chuyển về server mặc định.',
      'player_position': 'Tiến độ phát',
      'download_finished': 'Tải xong 🚀',
      'click_to_install': '(Bấm để cài đặt)',
      'verifying_file': 'Đang xác minh bản cập nhật...',
      'installing_cached': 'Bản cập nhật đã sẵn sàng, đang mở trình cài đặt...',
      'error_opening_link': 'Không thể mở trình cài đặt hoặc liên kết',
      'udid_register_title': 'Nhập mã UDID',
      'udid_update_title': 'Cập nhật UDID',
      'udid_hint': 'Dán mã UDID tại đây...',
      'udid_save': 'Lưu lại',
      'udid_copy': 'Sao chép UDID',
      'udid_copied': 'Đã sao chép UDID',
      'udid_deleted': '✅ Đã xóa UDID!',
      'udid_delete_btn': 'Xóa UDID',
      'udid_install_btn': 'Cài đặt ngay',
      'udid_get_btn': 'Lấy UDID',
      'udid_input_btn': 'Nhập UDID',
      'udid_update_btn': 'Cập nhật',
      'udid_registered_badge': 'ĐÃ ĐĂNG KÝ',
      'ios_service_title': 'iOS Premium Service',
      'ios_premium_desc':
          'Cần đăng ký UDID thiết bị để có thể cài đặt và cập nhật bản IPA Premium chính thức.',
      'ios_ready_desc':
          'Thiết bị của bạn đã được đăng ký UDID. Bạn có thể cài đặt phiên bản Premium IPA chính thức ngay bây giờ.',
      'premium_tab': 'Premium',
      'share_logs': 'Chia sẻ nhật ký',
      'share_logs_desc':
          'Gửi file log qua AirDrop, tin nhắn hoặc lưu vào Files',
      'share_logs_subject': 'TPhimX Log Files',
      'udid_auto_detected': '✅ Tự động nhận diện UDID thành công!',
      'udid_invalid': '❌ Mã UDID không hợp lệ: %m',
      'status_registered': 'Đã đăng ký',
      'status_not_registered': 'Chưa đăng ký',
      'notifications': 'Thông báo',
      'error_loading_notifications': 'Không thể tải thông báo',
      'login': 'Đăng nhập',
      'login_google': 'Đăng nhập với Google',
      'register': 'Đăng ký',
      'login_id': 'Tên tài khoản hoặc Email',
      'login_id_hint': 'Nhập username hoặc email của bạn',
      'password': 'Mật khẩu',
      'password_hint': 'Nhập mật khẩu của bạn',
      'create_account': 'Tạo tài khoản',
      'full_name': 'Họ và tên',
      'email': 'Email',
      'username': 'Tên tài khoản',
      'confirm_password': 'Xác nhận mật khẩu',
      'gender': 'Giới tính',
      'gender_male': 'Nam',
      'gender_female': 'Nữ',
      'gender_other': 'Khác',
      'no_notifications': 'Bạn chưa có thông báo nào',
      'error_login': 'Đăng nhập thất bại',
      'verify_email_msg': 'Vui lòng xác minh email để đăng nhập',
      'login_verify_required_title': 'Xác thực tài khoản',
      'login_verify_required_msg': 'Tài khoản của bạn chưa được xác thực email. Vui lòng truy cập website của chúng tôi (https://dongmephim.online) và đăng nhập để xác thực tài khoản nhé!',
      'login_success': 'Đăng nhập thành công',
      'logout_success': 'Đăng xuất thành công',
      'logout_confirm': 'Bạn có chắc chắn muốn đăng xuất?',
      'account_title': 'Tài khoản',
      'email_verified': 'Đã xác minh email',
      'app_slogan': 'Phim mới cực mượt - Xem là ghiền',
      'error_empty_fields': 'Vui lòng điền đầy đủ các trường',
      'error_password_mismatch': 'Mật khẩu xác nhận không khớp',
      'error_connection': 'Lỗi kết nối máy chủ',
      'login_required_notifications': 'Vui lòng đăng nhập để xem thông báo.',
      'my_list': 'Danh sách của tôi',
      'notifications_cleared': 'Đã xóa tất cả thông báo',
      'notifications_read_all': 'Đã đánh dấu tất cả là đã đọc',
      'appearance': 'Giao diện',
      'settings': 'Cài đặt',
      'font_size': 'Cỡ chữ',
      'font_size_desc': 'Điều chỉnh kích thước văn bản toàn ứng dụng',
      'font_family': 'Phông chữ',
      'font_outfit': 'Outfit (Mặc định)',
      'font_roboto': 'Roboto',
      'font_inter': 'Inter',
      'font_open_sans': 'Open Sans',
      'font_montserrat': 'Montserrat',
      'font_oswald': 'Oswald',
      'font_playfair': 'Playfair Display',
      'font_poppins': 'Poppins',
      'font_lato': 'Lato',
      'font_nunito': 'Nunito',
      'font_merriweather': 'Merriweather',
      'font_manrope': 'Manrope',
      'font_rubik': 'Rubik',
      'font_fira_sans': 'Fira Sans',
      'font_source_sans_3': 'Source Sans 3',
      'font_plus_jakarta_sans': 'Plus Jakarta Sans',
      'font_bebas_neue': 'Bebas Neue',
      'cache_management': 'Quản lý bộ nhớ đệm',
      'clear_cache': 'Xóa bộ nhớ đệm',
      'cache_cleared': 'Đã xóa bộ nhớ đệm thành công',
      'cache_empty': 'Bộ nhớ đệm trống',
      'cache_size': 'Dung lượng bộ nhớ: %size%',
      'permissions': 'Quền hạn & Bảo mật',
      'manage_permissions': 'Quản lý quyền ứng dụng',
      'manage_permissions_desc':
          'Mở cài đặt hệ thống để cấp/hủy các quyền đã yêu cầu',
      'reminder_set': 'Đã đặt nhắc nhở 🔔',
      'reminder_canceled': 'Đã hủy nhắc nhở',
      'delete_all': 'Xóa hết',
      'read_all': 'Đọc hết',
      'unread': 'Chưa đọc',
      'marked_read': 'Đã đọc',
      'permission_dnd_label': 'Quyền Không làm phiền',
      'permission_dnd_desc':
          'Bắt buộc để ứng dụng có thể tự động bật chế độ im lặng khi bạn xem phim, giúp trải nghiệm không bị gián đoạn.',
      'permission_alarm_label': 'Báo thức chính xác',
      'permission_alarm_desc': 'Bắt buộc để gửi thông báo lịch chiếu đúng giờ.',
      'view_all': 'Xem tất cả',
      'no_favorites': 'Chưa có phim yêu thích',
      'no_history': 'Lịch sử xem trống',
      'system': 'Hệ thống',
      'network_speed': 'Tốc độ mạng',
      'auto_quality': 'Tự động chất lượng',
      'auto_quality_desc': 'Tự động tối ưu chất lượng dựa trên tốc độ mạng',
      'show_speed_notif': 'Hiện tốc độ thông báo',
      'show_speed_notif_desc':
          'Hiện chỉ báo tốc độ trên thanh trạng thái & màn hình khóa',
      'speed_unit': 'Đơn vị tốc độ',
      'battery_optimization': 'Bỏ tối ưu pin (Chạy ngầm)',
      'ignore_battery_msg':
          'Để tốc độ mạng luôn chính xác và tải phim ổn định, vui lòng cho phép ứng dụng bỏ qua tối ưu hóa pin.',
      'episode_label': 'Tập %n%',
      'time_hour': '%n% giờ',
      'time_minute': '%n% phút',
      'time_second': '%n% giây',
      'time_just_now': 'Vừa xong',
      'time_seconds_ago': '%n% giây trước',
      'time_minutes_ago': '%n% phút trước',
      'time_hours_ago': '%n% giờ trước',
      'time_days_ago': '%n% ngày trước',
      'time_months_ago': '%n% tháng trước',
      'time_years_ago': '%n% năm trước',
      'num_k': 'K',
      'num_m': 'Tr',
      'num_b': 'Tỷ',
      'miracast_protection': 'Bảo vệ Miracast',
      'cast_to_tv': 'Phát lên TV',
      'speed_test': 'Kiểm tra tốc độ',
      'network': 'Mạng',
      'start_test': 'Bắt đầu đo',
      'network_wifi': 'WiFi',
      'network_mobile': 'Dữ liệu di động',
      'network_ethernet': 'Cáp mạng (Ethernet)',
      'network_usage': 'Lưu lượng đã dùng',
      'total': 'Tổng cộng',
      'testing': 'Đang đo...',
      'miracast_mirror': 'Miracast / Screen Mirror',
      'miracast_mirror_desc': 'Mở cài đặt phản chiếu hệ thống',
      'chromecast_desc': 'Phát video trực tiếp lên thiết bị Chromecast',
      'web_browser_cast': 'Dò Web (Browser)',
      'web_browser_cast_desc':
          'Mở link video trong trình duyệt có hỗ trợ truyền tải',
      'block_mirroring': 'Chặn phản chiếu (Bảo vệ)',
      'protection_on': 'Bảo vệ Miracast: BẬT (Chặn phản chiếu)',
      'protection_off': 'Bảo vệ Miracast: TẮT (Cho phép phản chiếu)',
      'miracast_detected':
          'Phát hiện phản chiếu màn hình. Vui lòng tắt Miracast để tiếp tục.',
      'searching_chromecast': 'Đang tìm kiếm thiết bị Chromecast...',
      'found_chromecast': 'Tìm thấy %n% thiết bị!',
      'no_chromecast_found': 'Không tìm thấy thiết bị nào.',
      'bg_new_episode_title': 'Tập mới: %n%',
      'bg_new_episode_body': 'Phim bạn yêu thích vừa có tập mới!',
      'select_device': 'Chọn thiết bị (%count)',
      'disconnect_cast': 'Ngắt kết nối Cast',
      'casting_to': 'Đang truyền tới',
      'no_streamable_url': 'Không tìm thấy link video để truyền',
      'stopped_casting': 'Đã dừng truyền video',
      'download_settings': 'Cài đặt tải xuống',
      'download_format': 'Định dạng video',
      'max_concurrent_downloads': 'Số tập tải cùng lúc',
      'download_queue': 'Hàng đợi tải',
      'download_path': 'Đường dẫn lưu trữ',
      'downloaded_series_progress': 'Đã tải %p%% (Tập %c%/%t%)',
      'download_completed': 'Tải hoàn tất',
      'download_channel_name': 'Quản lý tải xuống',
      'download_channel_desc': 'Thông báo về tiến độ và trạng thái tải phim',
      'download_all_completed': 'Đã tải xong tất cả %n% tập',
      'download_single_completed': 'Đã tải xong tập: %ep%',
      'download_error': 'Lỗi khi tải: %msg%',
      'delete_all_confirm': 'Xóa tất cả phim đã tải?',
      'delete_movie_confirm': 'Xóa phim này khỏi máy?',
      'offline_mode': 'Đang xem ngoại tuyến',
      'movie_removed_server': 'Phim đã bị gỡ khỏi Server. Tự động xóa sau 5s.',
      'priority_download': 'Tải ngay (Ưu tiên)',
      'storage_full': 'Bộ nhớ đầy, không thể tải thêm',
      'download_manager': 'Quản lý tải xuống',
      'cancel_download': 'Hủy tải',
      'pause_download': 'Tạm dừng',
      'resume_download': 'Tiếp tục',
      'all_episodes': 'tất cả tập',
      'adding_all_to_download': 'Đang thêm tất cả tập vào hàng chờ tải...',
      'cannot_download_episode': 'Không thể tải tập phim. Vui lòng thử lại!',
      'download_link_not_found': 'Không tìm thấy link tải cho tập phim này',
      'added_to_download': 'Đã thêm vào hàng chờ tải 📥',
      'download_all_started': 'Đã thêm %n% tập vào hàng chờ tải',
      'download_all_failed':
          'Không thể thêm tập phim nào. Kiểm tra kết nối mạng!',
      'download_all_partial': 'Đã thêm %s%/%t% tập. %f% tập thất bại',
      'downloading_all': 'Đang xử lý tải tất cả...',
      'no_internet_no_downloads': 'Không có kết nối & Chưa có phim tải về',
      'no_internet_msg':
          'Vui lòng kiểm tra kết nối internet để xem phim trực tuyến hoặc tải phim về xem ngoại tuyến.',
      'download_speed': 'Tốc độ: %s%',
      'episodes_count': 'Tập: %c%/%t%',
      'total_size': 'Dung lượng: %s% / %t%',
      'downloaded_movies': 'Phim đã tải',
      'episode_count_label': '%n% tập',
      'downloaded': 'Đã tải về',
      'delete': 'Xóa',
      'download_summary': 'Đang tải %n% phim',
      'downloading_count': 'Đang tải %n% phim',
      'episodes_completed': 'Đã tải %c%/%t% tập',
      'all_downloaded': 'Đã tải xong',
      'download_eta': 'ETA: %e%',
      'movies': 'Phim',
      'no_history_msg': 'Phim bạn tải xuống sẽ xuất hiện tại đây',
      'delete_selected_movies_msg':
          'Hành động này sẽ xóa các tập phim đã chọn khỏi thiết bị.',
      'delete_all_episodes_msg':
          'Hành động này sẽ xóa tất cả các tập phim của bộ này.',
      'local_playback_error':
          'Lỗi phát file cục bộ. File có thể bị hỏng hoặc thiếu dữ liệu (HLS segments).',
      'test_completed': 'Kiểm tra hoàn tất',
      'test_again': 'Đo lại',
      'speed_excellent': 'Tuyệt vời! Mượt mà cho 4K.',
      'speed_good': 'Rất tốt. Mượt mà cho HD.',
      'speed_stable': 'Ổn định. Tốt cho SD.',
      'speed_slow': 'Kết nối chậm. Có thể giật lag.',
      'api_server': 'Server API',
      'image_server': 'Server Ảnh',
      'no_notifications_desc':
          'Bạn chưa có thông báo nào mới. Hãy theo dõi các bộ phim yêu thích để nhận tin tức mới nhất!',
      // Coach Mark
      'coach_menu_title': 'Menu chính',
      'coach_menu_desc':
          'Chạm vào đây để mở menu: cài đặt ngôn ngữ, kiểm tra quyền, và nhiều tùy chọn khác.',
      'coach_search_title': 'Tìm kiếm phim',
      'coach_search_desc':
          'Chạm vào đây để tìm kiếm phim, diễn viên hoặc thể loại bạn yêu thích.',
      'coach_hero_title': 'Phim nổi bật',
      'coach_hero_desc':
          'Vuốt để khám phá những bộ phim đang hot và được đề xuất dành cho bạn.',
      'coach_filter_title': 'Bộ lọc thể loại',
      'coach_filter_desc':
          'Chọn thể loại phim bạn muốn xem: phim bộ, phim lẻ, hoạt hình, chiếu rạp...',
      'coach_movie_title': 'Danh sách phim',
      'coach_movie_desc':
          'Chạm vào bất kỳ bộ phim nào để xem chi tiết, tải xuống hoặc thêm vào yêu thích.',
      'coach_nav_title': 'Thanh điều hướng',
      'coach_nav_desc':
          'Di chuyển giữa Trang chủ, Tìm kiếm, Lịch chiếu, và Tài khoản tại đây.',
      'got_it': 'Đã hiểu!',
      'next': 'Tiếp theo',
      'coach_player_brightness_title': 'Độ Sáng Màn Hình',
      'coach_player_brightness_desc': 'Vuốt lên/xuống ở nửa bên trái màn hình để tăng/giảm độ sáng.',
      'coach_player_volume_title': 'Âm Lượng',
      'coach_player_volume_desc': 'Vuốt lên/xuống ở nửa bên phải màn hình để tăng/giảm âm lượng.',
      'coach_player_seek_title': 'Tua Video Nhanh',
      'coach_player_seek_desc': 'Nhấn đúp (Double Tap) vào nửa bên trái/phải màn hình để lùi/tiến 10 giây.',
      'comments': 'Bình luận',
      'write_comment': 'Viết bình luận...',
      'post': 'Đăng',
      'give_stars': 'Chọn số sao đánh giá (1-10)',
      'no_comments': 'Chưa có bình luận nào.',
      'register_website_msg': 'Vui lòng truy cập website của chúng tôi (https://dongmephim.online) để đăng ký tài khoản mới!',
      'rating_title': 'Đánh giá phim',
      'rating_submit': 'Gửi đánh giá',
      'rating_success': 'Đánh giá thành công!',
      'rating_val_label': '%n%/10 điểm',
      'unreleased_warning_title': 'Tập phim chờ chiếu ⏳',
      'unreleased_warning_body': 'Tập phim này chưa công chiếu.\nPhát sóng lúc: %time% - ngày %date%',
      'unreleased_countdown': 'Sắp chiếu sau: %countdown%',
      'subscription_vip_title': 'Đặc quyền DongMePhim VIP',
      'subscription_vip_desc': 'Xem phim UltraHD/4K không quảng cáo, đường truyền CDN VIP siêu nhanh, mở khóa toàn bộ kho phim bom tấn.',
      'upgrade_vip_btn': 'Nâng cấp ngay',
      'pkg_monthly': 'Gói tháng',
      'pkg_annual': 'Gói năm',
      'buy_package': 'Đăng ký gói',
      'payment_waiting': 'Đang chờ thanh toán...',
      'payment_instruction': 'Vui lòng quét mã VietQR bên dưới để thanh toán chuyển khoản qua SePay tự động.',
      'pay_confirm': 'Xác nhận đã chuyển khoản',
      'vip_server_locked_title': 'Nguồn phát giới hạn',
      'vip_server_locked_desc': 'Vui lòng nâng cấp gói để xem nguồn phát này!',
      'upgrade_now_btn': 'Nâng cấp ngay',
      'billing_history': 'Lịch sử hóa đơn',
      'view_invoice_web': 'Xem hóa đơn (Web)',
      'promo_empty_msg': 'Vui lòng nhập mã giảm giá!',
      'promo_invalid_msg': 'Mã giảm giá không hợp lệ!',
      'promo_system_error': 'Lỗi hệ thống khi xác thực mã giảm giá!',
      'promo_success_msg': 'Áp dụng mã giảm giá thành công!',
      'payment_status_pending': 'Đang chờ',
      'payment_status_approved': 'Đã duyệt',
      'payment_status_rejected': 'Từ chối',
      'promo_applied_msg': 'Đã áp dụng mã "%code%" (Giảm %discount%)',
      'compact_mode': 'Rút gọn',
      'now_playing': 'Đang chiếu',
      'video_file_blocked': 'DongMePhim không hỗ trợ mở video từ máy bạn. Hãy tìm kiếm phim trực tiếp trong ứng dụng.',
      // Fallback compatibility keys for older client versions or fallback strings
      'Anime & Hoạt Hình': 'Anime & Hoạt hình',
      'Mới cập nhật': 'Phim mới cập nhật',
      'Phim Lẻ Hay Nhất': 'Phim lẻ mới',
      'Phim Bộ Đặc Sắc': 'Phim bộ mới',
      'Xem nhiều nhất': 'Phim xem nhiều nhất',
      'TV Shows thực tế': 'TV Shows',
      'Phim Chiếu Rạp Bom Tấn': 'Phim chiếu rạp',
      'mark_read': 'Đánh dấu đã đọc',
      'mark_all_read': 'Đọc tất cả',
      'clear_all': 'Xóa tất cả',
      'open_movie': 'Mở phim',
      'current_episode': 'Tập hiện tại',
      'login_prompt_title': 'Yêu cầu đăng nhập',
      'login_prompt_desc': 'Bạn cần đăng nhập để xem các thông báo cập nhật phim cá nhân hóa từ hệ thống.',
      'login_now': 'Đăng nhập ngay',
      'login_required_watch_title': 'Yêu cầu đăng nhập',
      'login_required_watch_desc': 'Bạn cần đăng nhập tài khoản để xem bộ phim này.',
      'toast_marked_read': 'Đã đánh dấu đã đọc',
      'toast_marked_all_read': 'Đã đọc toàn bộ thông báo',
      'toast_cleared_all': 'Đã xóa toàn bộ thông báo',
      'no_schedule_found': 'Chưa có lịch chiếu nào.',
      'no_movies_day': 'Không có phim phát sóng ngày này.',
      'request_movie': 'Yêu cầu phim',
      'film_name': 'Tên phim',
      'original_name': 'Tên gốc',
      'publish_year': 'Năm sản xuất',
      'link_phim': 'Link phim (nếu có)',
      'author': 'Tác giả/Đạo diễn',
      'submit': 'Gửi',
      'sending': 'Đang gửi...',
      'request_success': 'Gửi yêu cầu phim thành công!',
      'request_failed': 'Gửi yêu cầu thất bại!',
      'enter_film_name': 'Vui lòng nhập tên phim!',
      'discord_server': 'Máy chủ Discord',
      'join_discord_server': 'Tham gia máy chủ Discord để cập nhật lịch chiếu, sự kiện và giao lưu',
      // Smart TV Keys
      'tv_unsupported_device': 'Thiết bị Samsung Smart TV chưa được hỗ trợ chính thức.',
      'tv_smarttv_enable': 'Giả lập Smart TV',
      'tv_exit_emulation': 'Thoát giả lập TV',
      'tv_smarttv_desc': 'Giả lập giao diện Smart TV cho desktop.',
      'tv_registering_device': 'Đang đăng ký thiết bị TV...',
      'tv_loading_config': 'Đang tải thông tin cấu hình...',
      'tv_init_success': 'Hoàn tất khởi tạo!',
      'tv_unsupported_title': 'Thiết Bị Chưa Hỗ Trợ',
      'tv_samsung_block_msg': 'Ứng dụng DongMePhim TV hiện chưa hỗ trợ hệ điều hành Tizen OS của Samsung TV hoặc thiết bị giả lập Samsung.\n\nVui lòng cài đặt và sử dụng ứng dụng trên Android TV hoặc Google TV.',
      'tv_exit_app': 'Thoát Ứng Dụng',
      'tv_waiting_confirm': 'Đang chờ xác nhận...',
      'tv_qr_expired': 'Mã QR đã hết hạn',
      'tv_refresh_qr': 'Làm mới QR',
      'tv_login_success': 'Đăng nhập TV thành công!',
      'tv_guest_mode_msg': 'Bạn đang xem ở chế độ Khách.',
      'tv_code_expired': 'Mã liên kết đã hết hạn!',
      'tv_get_new_code': 'Lấy mã mới',
      'tv_expired_after': 'Hết hạn sau: %time%',
      'tv_instructions': 'Hướng dẫn:',
      'tv_code_instruction_1': '1. Mở ứng dụng DongMePhim trên Điện thoại/Web.',
      'tv_code_instruction_2': '2. Bấm vào trang cá nhân hoặc Menu phụ.',
      'tv_code_instruction_3': '3. Chọn "Đăng nhập vào TV" và nhập mã phía trên.',
      'tv_qr_instruction_1': '1. Mở ứng dụng DongMePhim trên Điện thoại.',
      'tv_qr_instruction_2': '2. Chọn chức năng quét mã QR TV.',
      'tv_qr_instruction_3': '3. Quét mã QR trên TV và nhấn Đồng ý.',
      'tv_scan_qr_title': 'QUÉT MÃ QR KẾT NỐI',
      'tv_code_login_title': 'ĐĂNG NHẬP BẰNG MÃ TV',
      'tv_skip_login': 'Bỏ qua, trải nghiệm không đăng nhập',
      'tv_menu_home': 'Trang Chủ',
      'tv_menu_search': 'Tìm Kiếm',
      'tv_menu_series': 'Phim Bộ',
      'tv_menu_singles': 'Phim Lẻ',
      'tv_menu_profile': 'Tài Khoản',
      'tv_menu_logout': 'Đăng Xuất',
      'tv_load_home_error': 'Lỗi tải trang chủ TV!',
      'tv_logout_confirm_title': 'Đăng Xuất',
      'tv_logout_confirm_msg': 'Bạn có chắc muốn đăng xuất tài khoản khỏi TV này không?',
      'tv_cancel': 'Hủy bỏ',
      'tv_logout': 'Đăng xuất',
      'tv_search_dev': 'Tìm kiếm đang phát triển...',
      'tv_shelf_new': 'Phim Mới Cập Nhật',
      'tv_shelf_hot': 'Phim Hot Thịnh Hành',
      'tv_shelf_series': 'Phim Bộ Đặc Sắc',
      'tv_watch_now': 'Xem Ngay',
      'tv_info': 'Thông Tin',
      'tv_category_dev': 'Phân loại danh sách đang được cập nhật...',
      'tv_logout_account': 'Đăng Xuất Tài Khoản',
      'tv_movie_not_found': 'Không tìm thấy thông tin phim!',
      'tv_server_error': 'Lỗi kết nối máy chủ!',
      'tv_back': 'Quay Lại',
      'tv_episodes_list': 'DANH SÁCH TẬP PHIM',
      'tv_no_episodes': 'Không có tập phim nào!',
      'tv_no_description': 'Không có mô tả cho bộ phim này.',
      'tv_dpad_guide': 'Sử dụng phím điều hướng ◄ ▲ ▼ ► trên Remote • Nhấn OK để Chọn/Phát',
      'tv_dpad_guide_title': 'Hướng Dẫn Điều Hướng TV',
      'tv_dpad_guide_welcome': 'Chào mừng bạn đến với DongMePhim Smart TV! Dưới đây là cách điều khiển bằng Remote:',
      'tv_dpad_guide_arrows': 'Sử dụng cụm phím mũi tên ◄ ▲ ▼ ► (D-Pad) để di chuyển tiêu điểm giữa các mục phim, hàng phim và danh mục.',
      'tv_dpad_guide_ok': 'Nhấn nút OK / Select (Giữa D-Pad) để mở phim, phát video hoặc chọn tính năng.',
      'tv_dpad_guide_back': 'Nhấn nút BACK / ESC trên remote để quay lại hoặc đóng trình chiếu.',
      'tv_dpad_guide_hint': '💡 Gợi ý: Hãy chọn các phim nổi bật trong mục "Phim Mới Cập Nhật" hoặc "Phim Hot Thịnh Hành" để bắt đầu trải nghiệm nhé!',
      'tv_select_season': 'CHỌN PHẦN PHIM KHÁC',
      'select_season_hint': 'Chọn phần phim khác:',
      'tv_playing': 'Đang phát',
      'tv_paused': 'Đã tạm dừng',
      'tv_seek_forward': 'Tua nhanh +%seconds%s',
      'tv_seek_backward': 'Lùi lại -%seconds%s',
      'tv_player_loading': 'Đang tải nguồn phát chất lượng cao...',
      // --- Ad overlay keys ---
      'ad_label': 'Quảng cáo',
      'ad_vip_hint': 'Quảng cáo tài trợ — Nâng cấp VIP để tắt',
      'ad_skip': 'Bỏ qua quảng cáo',
      'ad_countdown': 'Có thể bỏ qua sau: %seconds%s',
      // --- Player UI keys ---
      'player_preparing': 'Đang chuẩn bị luồng phát...',
      'player_locked': 'Đã khóa màn hình phát!',
      'player_unlocked': 'Đã mở khóa trình phát.',
      'player_error_stream': 'Lỗi tải luồng phát video!',
      'tv_hint_seek': 'Tua',
      'tv_hint_volume': 'Âm lượng',
      'tv_hint_ok': 'Phát/Dừng',
      'tv_shelf_history': 'Lịch Sử Xem',
      'tv_shelf_favorites': 'Phim Yêu Thích',
      'tv_no_favorites': 'Chưa có phim yêu thích nào.',
      'tv_explore_now': 'Khám phá ngay',
      'tv_explore_hint': 'Hãy khám phá các bộ phim hấp dẫn tại Trang chủ!',
      'tv_app_version': 'Phiên bản ứng dụng',
      'tv_device_info': 'Thông tin thiết bị',
      // Log Viewer
      'log_sharing_prep': 'Đang chuẩn bị tệp nhật ký để chia sẻ...',
      'log_cleared': 'Đã xóa toàn bộ nhật ký!',
      'log_copied': 'Đã sao chép nhật ký chi tiết!',
      'log_copy_failed': 'Sao chép thất bại: %error%',
      // Movie Details
      'no_stream_found': 'Không tìm thấy nguồn phát!',
      'login_to_rate': 'Vui lòng đăng nhập để đánh giá phim!',
      'already_rated': 'Bạn đã đánh giá bộ phim này rồi!',
      'rating_submitting': 'Đang gửi đánh giá...',
      'rating_failed': 'Đánh giá thất bại. Vui lòng thử lại!',
      'comment_empty': 'Nội dung bình luận không được để trống.',
      'comment_success': 'Đăng bình luận thành công!',
      'comment_failed': 'Gửi bình luận thất bại. Thử lại sau!',
      'reply_empty': 'Nội dung phản hồi không được để trống.',
      'reply_submitting': 'Đang gửi trả lời...',
      'reply_success': 'Đăng phản hồi thành công!',
      'reply_failed': 'Gửi phản hồi thất bại. Thử lại sau!',
      'comment_liked': 'Đã thích bình luận ❤️',
      'comment_deleted': 'Đã xóa bình luận.',
      'comment_delete_title': 'Xóa bình luận?',
      'comment_delete_confirm': 'Bạn có chắc chắn muốn xóa bình luận này?',
      'login_to_comment': 'Vui lòng đăng nhập để bình luận về phim!',
      // Profile & VIP
      'vip_remaining': 'Còn',
      'vip_expiry_date': 'Đến',
      'vip_privileges': 'Đặc quyền',
      'billing_monthly_tab': 'Gói Tháng',
      'billing_annual_tab': 'Gói Năm',
      'billing_cycle_title': 'Chọn chu kỳ thanh toán',
      'payment_method_title': 'Phương thức thanh toán',
      'sepay_gateway_title': 'Cổng thanh toán SePay Tự Động',
      'sepay_gateway_desc': 'Quét mã thanh toán ngân hàng nhận gói ngay lập tức.',
      'manual_vietqr_title': 'Chuyển khoản VietQR Thủ công',
      'manual_vietqr_desc': 'Tự chuyển khoản & xác nhận để hệ thống kiểm tra.',
      'promo_code_title': 'Mã giảm giá (Promo Code)',
      'total_title': 'Tổng cộng',
      'price_includes_vat': 'Giá đã gồm VAT',
      'discount_label': 'Đã giảm',
      'renew_action': 'Gia hạn %pkg% ngay',
      'upgrade_action': 'Nâng cấp %pkg% ngay',
      'history_cleared': 'Đã xóa lịch sử xem phim',
      'history_clear_failed': 'Xóa lịch sử thất bại. Vui lòng thử lại!',
      'loading_vip_info': 'Đang tải thông tin gói cước...',
      'history_clear_confirm': 'Bạn có chắc chắn muốn xóa toàn bộ lịch sử xem phim?',
      'upgrade_vip_title': 'Nâng cấp tài khoản',
      'vietqr_scan_title': 'Quét mã VietQR chuyển khoản',
      'vietqr_scan_desc': 'Hệ thống tự động duyệt gói sau khi nhận chuyển khoản đúng cú pháp (Nội dung chuyển khoản).',
      'bank_label': 'Ngân hàng:',
      'account_no_label': 'Số tài khoản:',
      'account_name_label': 'Chủ tài khoản:',
      'amount_label': 'Số tiền:',
      'transfer_note_label': 'Nội dung chuyển khoản:',
      'open_sepay_pg_web': 'Mở cổng thanh toán SePay PG (Web)',
      'no_account_yet': 'Chưa có tài khoản? ',
      'register_now': 'Đăng ký ngay',
      'vip_card_desc_active': 'Đặc quyền xem phim chất lượng cao',
      'vip_card_desc_inactive': 'Đăng ký gói để mở kho phim bản quyền',
      'renew_btn': 'Gia hạn',
      'upgrade_btn': 'Nâng cấp',
      'choose': 'Chọn',
      'watch_history': 'Lịch sử xem phim',
      'favorites_list': 'Danh sách yêu thích',
      'status_pending': 'Đang chờ',
      'status_approved': 'Đã duyệt',
      'status_rejected': 'Từ chối',
      'tv_link_title': 'Liên kết Smart TV',
      'tv_scan_qr_title_btn': 'Quét mã QR Smart TV',
      'tv_scan_qr_desc_btn': 'Quét mã QR hiển thị trên TV để kết nối nhanh',
      'creating_tx': 'Đang tạo giao dịch...',
      'payment_pending_msg': 'Yêu cầu thanh toán đang chờ duyệt! Vui lòng tải lại trang sau 1-2 phút.',
      'payment_open_failed': 'Không thể mở cổng thanh toán. Hãy quét mã QR chuyển khoản.',
      'confirm_transferred': 'Xác nhận đã chuyển khoản',
      'no_favorites_yet': 'Chưa có phim yêu thích nào.',
      'tv_login_by_code': 'Đăng nhập vào TV bằng mã',
      'tv_login_enter_code': 'Nhập mã 8 ký tự hiển thị trên TV của bạn',
      // QR Scan
      'qr_invalid': 'Mã QR không hợp lệ!',
      'qr_read_error': 'Lỗi đọc mã QR: %error%',
      'login_on_phone_first': 'Vui lòng đăng nhập trên điện thoại trước!',
      'qr_scan_failed': 'Quét mã QR thất bại!',
      'qr_expired': 'Mã QR không hợp lệ hoặc đã hết hạn!',
      'server_conn_error': 'Lỗi kết nối máy chủ: %error%',
      // TV Pairing & Link Confirm
      'pairing_success': 'Ghép nối thiết bị thành công!',
      'pairing_confirm_error': 'Lỗi xác nhận liên kết!',
      'conn_error': 'Lỗi kết nối: %error%',
      'pairing_rejected': 'Đã từ chối liên kết TV!',
      'agree_login_tv': 'Đồng ý & Đăng nhập TV',
      'tv_paired_success': 'Thiết bị TV đã được ghép nối thành công!',
      'confirm_btn': 'Xác nhận',
      'tv_pair_code_invalid': 'Vui lòng nhập đầy đủ 4 chữ số!',
      'tv_pair_code_incorrect': 'Mã xác nhận TV không chính xác!',
      'tv_pair_code_expired_msg': 'Mã xác nhận TV không hợp lệ hoặc đã hết hạn!',
      'server_conn_error_retry': 'Lỗi kết nối máy chủ. Vui lòng thử lại!',
      'tv_login_title_modal': 'Đăng Nhập Vào TV',
      'tv_login_enter_code_desc': 'Nhập mã hiển thị trên Smart TV của bạn để kết nối nhanh tài khoản:',
      'cancel_btn': 'Hủy bỏ',
      'tv_confirm_login_title': 'Xác Nhận Đăng Nhập TV',
      'tv_confirm_login_desc': 'Bạn có muốn đăng nhập tài khoản của mình vào thiết bị TV này không?',
      'tv_device_info_title': 'THÔNG TIN THIẾT BỊ TV',
      'tv_device_name_label': 'Tên thiết bị:',
      'tv_device_os_label': 'Hệ điều hành:',
      'tv_device_model_label': 'Model máy:',
      'tv_device_ip_label': 'Địa chỉ IP:',
      'tv_device_location_label': 'Vị trí:',
      'tv_device_isp_label': 'Nhà mạng:',
      'reject_btn': 'Từ chối',
      // TV Player Screen
      'tv_no_stream_found': 'Không tìm thấy nguồn phát cho tập này!',
      'tv_conn_error': 'Lỗi kết nối máy chủ!',
      // TV Profile Tab
      'switched_to_vi': 'Đã chuyển sang Tiếng Việt',
      'switched_to_en': 'Đã chuyển sang Tiếng Anh',
      'exit_tv_emulator': 'Đã thoát chế độ giả lập TV',
      // Video Player & Ads
      'server_no_stream': 'Không tìm thấy luồng phát trên server này!',
      'ep_not_updated_on_server': 'Tập phim hiện tại chưa cập nhật trên server này!',
      'intro_skipped': 'Đã bỏ qua Intro',
      'outro_skipped': 'Đã bỏ qua Outro',
      'player_no_stream': 'Không tìm thấy nguồn phát cho tập này!',
      'play_speed_toast': 'Tốc độ phát: %speed%x',
      'ad_error_skip': 'Lỗi quảng cáo - Bỏ qua',
      'ad_load_failed': 'Không thể tải video quảng cáo từ hệ thống.',
      'ad_loading_yt': 'Đang phát quảng cáo YouTube...',
      'sponsored_link': 'Liên kết tài trợ',
      'next_video_countdown': 'Video tiếp theo sau %seconds%',
      'playlist_drawer_title': 'DANH SÁCH TẬP',
      // API Services
      'sync_success': 'Đồng bộ dữ liệu thành công!',
      'sync_unexpected_error': 'Lỗi kết nối hoặc lỗi bất ngờ: %error%',
      'skip_outro': 'Bỏ qua Outro',
      'subtitle_settings': 'Cài đặt phụ đề',
      'play_now': 'Phát ngay',
      'rate_label': 'Đánh giá',
      'anonymous': 'Ẩn danh',
      'api_url_label': 'ĐƯỜNG DẪN API (URL)',
      'sub_mode_off': 'Tắt',
      'sub_mode_primary': 'Đơn ngữ',
      'sub_mode_bilingual': 'Song ngữ',
      'sub_mode_label': 'Chế độ phụ đề: %mode%',
      'select_primary_sub': '--- CHỌN PHỤ ĐỀ CHÍNH ---',
      'select_secondary_sub': '--- CHỌN PHỤ ĐỀ PHỤ ---',
      'currently_selected': ' (Đang chọn)',
      'select_speed': '--- CHỌN TỐC ĐỘ PHÁT ---',
      'speed_normal': 'Bình thường',
      'switch_episode': '--- CHUYỂN TẬP PHIM ---',
      'prev_episode_label': 'Tập trước: %name%',
      'next_episode_label': 'Tập tiếp theo: %name%',
      'tv_select_server_section': '--- CHỌN NGUỒN PHÁT (SERVER) ---',
      'episode_list_playlist': 'Danh sách tập phim (Playlist)',
      'episode_list': 'Danh sách tập',
      'play_speed': 'Tốc độ phát',
      'server': 'Nguồn phát',
      'default_server': 'Nguồn phát mặc định',
      'close_settings': 'Đóng cài đặt',
      'sub_style_title': 'CÀI ĐẶT KIỂU DÁNG PHỤ ĐỀ',
      'sub_font_size': 'CỠ CHỮ PHỤ ĐỀ',
      'sub_color': 'MÀU CHỮ PHỤ ĐỀ',
      'sub_border': 'KIỂU VIỀN PHỤ ĐỀ',
      'sub_opacity': 'ĐỘ MỜ NỀN PHỤ ĐỀ',
      'sub_pos': 'VỊ TRÍ PHỤ ĐỀ PHỤ',
      'sub_color_white': 'Trắng',
      'sub_color_yellow': 'Vàng',
      'sub_color_green': 'Xanh lá',
      'sub_color_blue': 'Xanh lam',
      'sub_border_shadow': 'Đổ bóng',
      'sub_border_stroke': 'Viền chữ',
      'sub_border_none': 'Không viền',
      'sub_pos_top': 'Phía trên',
      'sub_pos_bottom': 'Phía dưới',
      'primary_sub_label': 'Phụ đề chính',
      'secondary_sub_label': 'Phụ đề phụ',
      'playback_speed': 'Tốc độ phát',
      'sub_on': 'Bật',
      'date_prefix': 'ngày',
      'episode_prefix': 'Tập',
      'next_episode_fallback': 'Tập tiếp theo',
      'broadcast_single_full': 'Trọn bộ bản đẹp sẽ phát sóng vào %time%',
      'broadcast_single_standard': 'Phim sẽ phát sóng vào %time%',
      'broadcast_series_full': 'Trọn bộ sẽ phát sóng vào %time%',
      'broadcast_series_final': 'Tập cuối sẽ phát sóng vào %time%',
      'broadcast_series_standard': '%episode% sẽ phát sóng vào %time%',
      'countdown_days': 'ngày',
      'countdown_hours': 'giờ',
      'countdown_minutes': 'phút',
      'countdown_seconds': 'giây',
      'countdown_unreleased': 'Chưa công chiếu',
      'broadcast_countdown_label': 'Sắp chiếu sau',
      // Subscription & Coupon
      'renew_same_pkg_title': 'Gia hạn gói cước',
      'renew_same_pkg_desc': 'Bạn đang dùng gói %pkg%. Gia hạn sẽ cộng thêm thời hạn vào ngày hết hạn hiện tại.',
      'switch_pkg_title': 'Chuyển đổi gói cước',
      'switch_pkg_desc': 'Bạn đang dùng gói %current%. Chuyển sang gói %new% sẽ đặt lại thời hạn từ đầu. Tiếp tục?',
      'upgrade_from_free_title': 'Nâng cấp lên VIP',
      'upgrade_from_free_desc': 'Chọn chu kỳ thanh toán để bắt đầu sử dụng đặc quyền VIP.',
      'billing_monthly': 'Hàng tháng',
      'billing_annual': 'Hàng năm',
      'savings_amount': 'Tiết kiệm %amount%',
      'coupon_input_hint': 'Nhập mã giảm giá',
      'coupon_apply_btn': 'Áp dụng',
      'coupon_applied_label': 'Đã áp dụng mã',
      'coupon_expiry_label': 'Hết hạn: %date%',
      'coupon_savings_label': 'Tiết kiệm',
      'original_price_label': 'Giá gốc',
      'discounted_price_label': 'Giá sau giảm',
      'open_checkout_web': 'Mở trang thanh toán (Web)',
    },
    'en': {
      'preparing': 'Preparing...',
      'logout': 'Logout',
      'app_name': 'DongMePhim',
      'ok': 'OK',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'check_update': 'Check for Updates',
      'downloading': 'Downloading',
      'download_fetching_playlist': 'Fetching playlist...',
      'download_downloading_segments': 'Downloading segment %c%/%t%...',
      'download_merging_video': 'Merging video...',
      'downloading_status': 'Downloading: %p%% • %s% • ETA: %e%',
      'pending': 'Pending',
      'paused': 'Paused',
      'notification_canceled': 'Notification canceled',
      'opening_external_browser': 'Opening external browser...',
      'offline_no_downloads_title': 'No downloads yet',
      'offline_no_downloads_msg':
          'You are offline and have no downloaded movies available.',
      'login_required': 'Please login to continue.',
      'account_banned_title': 'Account banned',
      'exit_app': 'Exit app',
      'verify_email': 'Verify email',
      'verifying_email': 'Verifying email...',
      'verify_success': 'Verification successful',
      'verify_success_msg': 'Your email has been verified successfully.',
      'verify_failed': 'Verification failed',
      'verify_failed_msg':
          'Could not verify your email. The link may be expired or invalid.',
      'error': 'Error',
      'success': 'Success',
      'permissions_required': 'Permissions required',
      'camera_permission_denied': 'Camera Access Denied',
      'grant_camera_permission': 'Grant Camera Permission',
      'storage_permission_msg':
          'App needs file management permission to save logs and download apps.',
      'grant': 'Grant',
      'skip': 'Skip',
      'retry': 'Retry',
      'network_error': 'No network connection',
      'update_available': 'New update available',
      'update_now': 'Update Now',
      'later': 'Later',
      'no_movies': 'No movies found',
      'error_loading_data': 'Failed to load data',
      'loading_data': 'Loading data...',
      'no_changelog': 'No update history available',
      'new_update_movies': 'Newest Movies',
      'hot_movies': 'Hot Movies',
      'anime_cartoon': 'Anime & Animation',
      'series_movies': 'New Series',
      'single_movies': 'New Singles',
      'cartoon_movies': 'Cartoons',
      'tv_shows': 'TV Shows',
      'theater_movies': 'Theaters',
      'search': 'Search',
      'home': 'Home',
      'categories': 'Categories',
      'schedule': 'Schedule',
      'logs': 'Logs',
      'clear_logs_confirm': 'Clear all logs?',
      'clear_logs_msg': 'This will delete all existing log files.',
      'profile': 'Profile',
      'app_premium': 'Mobile Premium',
      'connecting': 'Connecting...',
      'retry_connection': 'Retry Connection',
      'more': 'More',
      'watch_now': 'Watch Now',
      'watch_resume': 'Resume %ep%',
      'admin_scanning': 'Scanning new episodes for the movie...',
      'admin_scan_success_added': 'Found and updated %count% new episodes successfully!',
      'admin_scan_up_to_date': 'Movie is already synced. No new episodes found.',
      'admin_scan_error': 'Error scanning new episodes: %error%',
      'admin_scan_btn': 'Scan episodes',
      'admin_scanning_btn': 'Scanning...',
      'add_favorite': 'Favorite',
      'favorite_added': 'Added to favorites ❤️',
      'favorite_removed': 'Removed from favorites',
      'login_required_favorites': 'Please log in to save favorite movies.',
      'tv_add_favorite': 'Favorite',
      'trending_categories': 'What are you interested in?',
      'see_all': 'See All',
      'permission_storage_label': 'Storage & File Management',
      'permission_storage_desc':
          'Required to download movies and save app logs.',
      'permission_notif_label': 'Push Notifications',
      'permission_notif_desc':
          'Receive notifications for new episodes or schedules.',
      'permission_install_label': 'Install Applications',
      'permission_install_desc': 'Required for automatic version upgrades.',
      'permission_nearby_devices_label': 'Nearby Devices',
      'permission_nearby_devices_desc':
          'Required to search and connect to Cast/TV devices in the local network.',
      'permission_bluetooth_label': 'Bluetooth (Scanning)',
      'permission_bluetooth_desc':
          'Necessary to detect wireless casting devices nearby.',
      'permission_nearby_devices_denied':
          'Nearby devices permission denied. Cannot scan for TV.',
      'press_back_again': 'Press back again to exit',
      'player_settings': 'Player Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'vi_lang': 'Vietnamese',
      'en_lang': 'English',
      'loading_progress': 'Preparing data...',
      'splash_check_permissions': 'Checking permissions...',
      'splash_init_language': 'Initializing language...',
      'splash_config_system': 'Configuring system...',
      'splash_init_download': 'Initializing downloader...',
      'splash_ios_no_access': 'You do not have access to this application.',
      'splash_init_failed': 'Initialization failed',
      'splash_error_title': 'Oops! Something went wrong',
      'splash_error_copy': 'Copy Error',
      'splash_error_copied': 'Error code copied!',
      'splash_browser_error': 'Could not open browser',
      'splash_get_access': 'Get app access',
      'splash_safari_note':
          'Note: You need to install the verification profile after Safari opens.',
      'maintenance_title': 'System Under Maintenance',
      'maintenance_msg':
          'We are upgrading our system to provide a better experience. Please check back in a few minutes.',
      'check_permissions': 'Checking permissions',
      'please_grant_all': 'Please grant required permissions to continue.',
      'go_to_settings': 'Go to Settings',
      'permissions_mandatory': 'Mandatory Permissions',
      'permissions_optional': 'Optional Permissions',
      'granted': 'Granted',
      'denied': 'Denied',
      'continue': 'Continue',
      'permission_location_label': 'Location',
      'permission_location_desc':
          'Required for accurate network speed testing.',
      'permission_nearby_label': 'Nearby Devices',
      'permission_nearby_desc': 'Used to find and cast video to TV.',
      'speed_test_error':
          'Could not start speed test. Please grant location permission or try again later.',
      'feature_dev': 'Feature under development',
      'feature_under_dev': 'Feature "%label" is under development',
      'coming_soon': 'Coming Soon',
      'coming_soon_msg':
          'This feature will be available in future updates. Please check back later!',
      'earn_money': 'Earn Money',
      'episodes': 'Episodes',
      'episode': 'Episode',
      'loading_home': 'Loading homepage...',
      'loading_movie': 'Loading movie info...',
      'all_movies_count': '%count movies',
      'recommendation': 'Suggestions',
      'no_episodes': 'No episodes available',
      'not_found_movie': 'Movie not found',
      'select_server': 'Select Server',
      'related_parts': 'Which part?',
      'series_parts': 'Which part?',
      'actors': 'Cast',
      'no_actors': 'No cast info available',
      'download': 'Download',
      'download_label': 'Download speed',
      'upload_label': 'Upload speed',
      'share': 'Share',
      'favorite_list': 'Favorites',
      'collapse': 'Collapse',
      'show_more': 'Show more',
      'broadcast_msg': '%prefix% will broadcast at %time%. Don\'t miss it 😙',
      'broadcast_final_msg':
          'Don\'t miss %prefix% (Final) broadcasting at %time% 🥹',
      'broadcast_suffix':
          'Next episode will broadcast at %time%. Stay tuned 😙',
      'final_ep': 'Final Episode',
      'final_part': 'Final',
      'current_version': 'Current Version: %version%',
      'update_history': 'Update History',
      'general_settings': 'General Settings',
      'app_settings': 'App Settings',
      'community_support': 'Community & Support',
      'legal': 'Legal',
      'clear_cache_msg':
          'Are you sure you want to clear all temporary files and cache?',
      'cache_cleared': 'Cache cleared',
      'session_expired': 'Session Expired',
      'load_error': 'Failed to load information',
      'login_again_msg': 'Please login again to continue',
      'up_to_date': 'You are on the latest version (%version%)',
      'discord_server': 'Discord Server',
      'join_discord_server': 'Join our Discord server for schedules, events and chat',
      'update_error': 'Failed to check for updates',
      'checking_update': 'Checking for new version...',
      'whats_new': 'What\'s new:',
      'version_label': 'Version %version%',
      'volume': 'Volume',
      'speed': 'Speed',
      'skip_intro': 'Skip Intro',
      'auto_next_ep': 'Auto Next Episode',
      'skip_outro_next': 'Skip Outro / Next',
      'prep_next_ep': 'Preparing next episode...',
      'video_error': 'Failed to load video. Please try again!',
      'search_hint': 'Search movies, actors...',
      'searching': 'Searching...',
      'search_results': 'Results (%count)',
      'search_no_results': 'No results found for "%query"',
      'search_hot_title': '🔥 Trending Searches',
      'search_input_prompt': 'Types keywords to find movies',
      'clear_filter': 'Clear filter',
      'category_label': 'Category: %name',
      'views_count': '%count views',
      'movie_series': 'Series',
      'movie_single': 'Single',
      'year_label': 'Year %year',
      'today': 'Today',
      'loading_schedule': 'Loading schedule...',
      'no_schedule_today': 'No schedule today',
      'no_schedule_date': 'No schedule on %date',
      'unknown_episode': 'Episode ???',
      'watching': 'Watching',
      'my_list_long': 'My Movie List',
      'tv_login': 'SmartTV Login',
      'tv_smarttv_enable': 'Smart TV Emulator',
      'tv_exit_emulation': 'Exit TV Emulation',
      'tv_smarttv_desc': 'Emulate Smart TV interface for desktop.',
      'fb_fanpage': 'Facebook Fanpage',
      'tg_channel': 'Telegram Channel',
      'zalo_group': 'Zalo Group',
      'tg_support': 'Telegram Support',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'forgot_password': 'Forgot Password?',
      'account_title': 'Account',
      'save_changes': 'Save Changes',
      'not_open_link': 'Could not open link',
      'close': 'Close',
      'cannot_download_update': 'Could not download update',
      'download_failed_network': 'Download failed: Network error 🌐',
      'download_failed_server': 'Download failed: Server error (404/500) 🚫',
      'login_required_history': 'Please login to view watch history.',
      'error_unknown': 'An unknown error occurred',
      'resolver_error': 'Resolver error: %error',
      'no_sources_found': 'No valid streaming sources found for this episode.',
      'all_sources_failed': 'All streaming sources failed to load.',
      'player_source_fallback':
          'Source failed, trying source %current%/%total%...',
      'TXA_PB1': 'New Series',
      'TXA_PL1': 'New Singles',
      'TXA_NEW1': 'Newly Updated',
      'TXA_HOT1': 'Hot Movies',
      'TXA_HH1': 'Anime & Cartoons',
      'TXA_TV1': 'TV Shows',
      'TXA_CR1': 'Theatrical Movies',
      'TXA_LIST1': 'Movie List',
      'player_brightness': 'Brightness',
      'player_audio': 'Audio',
      'player_speed': 'Playback Speed',
      'loading_video': 'Loading video...',
      'player_lock': 'Lock Screen',
      'player_unlock': 'Unlock',
      'player_play': 'Play',
      'player_pause': 'Pause',
      'player_close': 'Close Player',
      'player_show_clock': 'Clock',
      'player_clock_format': 'Clock Format',
      'player_dnd_auto': 'Auto "Do Not Disturb"',
      'player_episodes': 'Episode List',
      'player_gesture_hint': 'Swipe to adjust brightness/volume',
      'player_fast_forward_2x': 'Fast Forwarding 2x',
      'player_seek_forward': 'Seek forward %count s',
      'miracast_detected':
          'Screen mirroring detected. Please disable Miracast to continue.',
      'player_seek_backward': 'Seek backward %count s',
      'player_watermark': 'TPhimX Premium',
      'player_ratio': 'Ratio',
      'player_audio_track': 'Audio',
      'player_seek_hint_short': 'Double Tap',
      'player_subtitle': 'Subtitle',
      'player_system_control_blocked':
          'Controlled by app, manual change disabled',
      'player_start_in': 'Starts in',
      'prev_ep': 'Prev Ep',
      'next_ep': 'Next Ep',
      'current_label': 'Current',
      'server_switch_hint': 'Switch server to watch from another source',
      'server_ep_unavailable_title': 'Episode Unavailable',
      'server_ep_unavailable_msg':
          'Episode %ep is not available on %server. Auto-switching to default server.',
      'player_position': 'Playback position',
      'download_finished': 'Download finished 🚀',
      'click_to_install': '(Click to install)',
      'verifying_file': 'Verifying update file...',
      'installing_cached': 'Update ready, opening installer...',
      'error_opening_link': 'Could not open installer or link',
      'udid_register_title': 'Input UDID',
      'udid_update_title': 'Update UDID',
      'udid_hint': 'Paste UDID here...',
      'udid_save': 'Save',
      'udid_copy': 'Copy UDID',
      'udid_copied': 'UDID copied',
      'udid_deleted': '✅ UDID deleted!',
      'udid_delete_btn': 'Delete UDID',
      'udid_install_btn': 'Install Now',
      'udid_get_btn': 'Get UDID',
      'udid_input_btn': 'Input UDID',
      'udid_update_btn': 'Update',
      'udid_registered_badge': 'REGISTERED',
      'ios_service_title': 'iOS Premium Service',
      'ios_premium_desc':
          'Need to register device UDID to install and update the official Premium IPA.',
      'ios_ready_desc':
          'Your device is registered. You can install the official Premium IPA now.',
      'premium_tab': 'Premium',
      'share_logs': 'Share Logs',
      'share_logs_desc':
          'Send log files via AirDrop, messages or save to Files',
      'no_logs_found': 'No log files found',
      'share_logs_subject': 'DongMePhim Log Files',
      'udid_auto_detected': '✅ UDID auto-detected successfully!',
      'udid_invalid': '❌ Invalid UDID code: %m',
      'status_registered': 'Registered',
      'status_not_registered': 'Not Registered',
      'notifications': 'Notifications',
      'error_loading_notifications': 'Could not load notifications',
      'screenshot_detected': 'Screenshot detected',
      'share_screenshot': 'Share screenshot',

      'exact_alarm_permission_denied': 'Missing exact alarm permission.',
      'notification_permission_denied': 'Notification permission denied.',
      'notification_scheduled': 'Reminder set 🔔',
      'notification_cancelled': 'Reminder cancelled',
      'notification_time_passed': 'Broadcast time has passed',
      'update_checking': 'Checking for new version...',
      'login': 'Login',
      'login_google': 'Login with Google',
      'register': 'Register',
      'login_id': 'Username or Email',
      'login_id_hint': 'Enter your username or email',
      'password': 'Password',
      'password_hint': 'Enter your password',
      'create_account': 'Create Account',
      'full_name': 'Full Name',
      'email': 'Email',
      'username': 'Username',
      'confirm_password': 'Confirm Password',
      'gender': 'Gender',
      'gender_male': 'Male',
      'gender_female': 'Female',
      'gender_other': 'Other',
      'no_notifications': 'No notifications found',
      'no_notifications_desc': 'New notifications will appear here.',
      'error_login': 'Login failed',
      'verify_email_msg': 'Please verify your email to login',
      'login_verify_required_title': 'Account Verification',
      'login_verify_required_msg': 'Your account is not email-verified. Please visit our website (https://dongmephim.online) and log in to verify your account!',
      'login_success': 'Login successful',
      'logout_success': 'Logout successful',
      'logout_confirm': 'Are you sure you want to logout?',
      'email_verified': 'Email verified',
      'app_slogan': 'Smooth streaming - Watch and crave',
      'error_empty_fields': 'Please fill in all fields',
      'error_password_mismatch': 'Confirm password does not match',
      'error_connection': 'Server connection error',
      'login_required_notifications': 'Please login to view notifications.',
      'my_list': 'My List',
      'notifications_cleared': 'All notifications cleared',
      'notifications_read_all': 'All marked as read',
      'appearance': 'Appearance',
      'settings': 'Settings',
      'font_size': 'Font Size',
      'font_size_desc': 'Adjust the text size across the entire app',
      'font_family': 'Font Family',
      'font_outfit': 'Outfit (Default)',
      'font_roboto': 'Roboto',
      'font_inter': 'Inter',
      'font_open_sans': 'Open Sans',
      'font_montserrat': 'Montserrat',
      'font_oswald': 'Oswald',
      'font_playfair': 'Playfair Display',
      'font_poppins': 'Poppins',
      'font_lato': 'Lato',
      'font_nunito': 'Nunito',
      'font_merriweather': 'Merriweather',
      'font_manrope': 'Manrope',
      'font_rubik': 'Rubik',
      'font_fira_sans': 'Fira Sans',
      'font_source_sans_3': 'Source Sans 3',
      'font_plus_jakarta_sans': 'Plus Jakarta Sans',
      'font_bebas_neue': 'Bebas Neue',
      'cache_management': 'Cache Management',
      'clear_cache': 'Clear Cache',
      'cache_empty': 'Cache is empty',
      'cache_size': 'Cache size: %size%',
      'reminder_set': 'Reminder set 🔔',
      'reminder_canceled': 'Reminder canceled',
      'broadcast_reminder_title': 'Upcoming: %name%',
      'broadcast_reminder_body':
          '%movie% will start in %minutes% minutes. Don\'t miss it!',
      'view_movie_detail': 'View Detail',
      'bg_new_episode_title_simple': 'New Episode: %n%',
      'broadcast_now_title': 'Now Broadcasting: %name%',
      'broadcast_now_body': 'Movie %movie% is now broadcasting. Watch now!',
      'delete_all': 'Clear All',
      'read_all': 'Read All',
      'unread': 'Unread',
      'marked_read': 'Read',
      'permission_dnd_label': 'Do Not Disturb Permission',
      'permission_dnd_desc': 'Allow app to manage notification sounds.',
      'permission_alarm_label': 'Exact Alarm',
      'permission_alarm_desc':
          'Required to send showtime notifications on time.',
      'view_all': 'View all',
      'no_favorites': 'No favorites yet',
      'no_history': 'Empty watch history',
      'permissions': 'Permissions & Security',
      'manage_permissions': 'Manage App Permissions',
      'manage_permissions_desc':
          'Open system settings to grant or revoke requested permissions',
      'system': 'System',
      'network_speed': 'Network Speed',
      'auto_quality': 'Auto Quality',
      'auto_quality_desc':
          'Automatically optimize quality based on network speed',
      'show_speed_notif': 'Show speed in notification',
      'show_speed_notif_desc':
          'Show speed indicator on status bar & lock screen',
      'speed_unit': 'Speed Unit',
      'battery_optimization': 'Ignore Battery Optimization',
      'ignore_battery_msg':
          'To ensure accurate network speed and stable downloads, please allow the app to ignore battery optimization.',
      'episode_label': 'Episode %n%',
      'time_hour': '%n%h',
      'time_minute': '%n%m',
      'time_second': '%n%s',
      'time_just_now': 'Just now',
      'time_seconds_ago': '%n%s ago',
      'time_minutes_ago': '%n%m ago',
      'time_hours_ago': '%n%h ago',
      'time_days_ago': '%n%d ago',
      'time_months_ago': '%n%mo ago',
      'time_years_ago': '%n%y ago',
      'num_k': 'K',
      'num_m': 'M',
      'num_b': 'B',
      'miracast_protection': 'Miracast Protection',
      'cast_to_tv': 'Cast to TV',
      'speed_test': 'Speed Test',
      'network': 'Network',
      'start_test': 'Start Test',
      'network_wifi': 'WiFi',
      'speed_excellent': 'Excellent',
      'speed_good': 'Good',
      'speed_stable': 'Stable',
      'speed_slow': 'Slow',
      'test_completed': 'Test Completed',
      'test_again': 'Test Again',
      'api_server': 'API Server',
      'image_server': 'Image Server',
      'error_search': 'Search Error',
      'vi': 'HOANG SA & TRUONG SA BELONG VIET NAM',
      'network_mobile': 'Mobile Data',
      'network_ethernet': 'Ethernet',
      'network_usage': 'Data Usage',
      'total': 'Total',
      'testing': 'Testing...',
      'miracast_mirror': 'Miracast / Screen Mirror',
      'miracast_mirror_desc': 'Open system screen mirroring settings',
      'chromecast_desc': 'Stream directly to Chromecast devices',
      'web_browser_cast': 'Web Browser (Cast)',
      'web_browser_cast_desc':
          'Open video link in browser with casting support',
      'block_mirroring': 'Block Mirroring (Protection)',
      'protection_on': 'Protection: ON (Block mirroring)',
      'protection_off': 'Protection: OFF (Allow mirroring)',
      'searching_chromecast': 'Searching for Chromecast devices...',
      'found_chromecast': 'Found %n% devices!',
      'no_chromecast_found': 'No devices found.',
      'bg_new_episode_title': 'New Episode: %n%',
      'bg_new_episode_body': 'Your favorite movie just got a new episode!',
      'select_device': 'Select device (%count)',
      'disconnect_cast': 'Disconnect Cast',
      'casting_to': 'Casting to',
      'no_streamable_url': 'No streamable URL found for casting',
      'stopped_casting': 'Stopped casting',
      'download_settings': 'Download Settings',
      'download_format': 'Video Format',
      'max_concurrent_downloads': 'Concurrent Downloads',
      'download_queue': 'Download Queue',
      'download_path': 'Storage Path',
      'downloaded_series_progress': 'Downloaded %p%% (Ep %c%/%t%)',
      'download_completed': 'Download Completed',
      'download_channel_name': 'Download Management',
      'download_channel_desc': 'Notifications for download progress and status',
      'download_all_completed': 'All %n% episodes downloaded',
      'download_single_completed': 'Downloaded episode: %ep%',
      'download_error': 'Download error: %msg%',
      'delete_all_confirm': 'Delete all downloaded movies?',
      'delete_movie_confirm': 'Delete this movie from device?',
      'offline_mode': 'Offline Playback',
      'movie_removed_server': 'Movie removed from server. Deleting in 5s.',
      'priority_download': 'Download Now (Priority)',
      'storage_full': 'Storage full, cannot download',
      'download_manager': 'Download Manager',
      'cancel_download': 'Cancel',
      'pause_download': 'Pause',
      'resume_download': 'Resume',
      'all_episodes': 'all episodes',
      'adding_all_to_download': 'Adding all episodes to download queue...',
      'cannot_download_episode':
          'Could not download episode. Please try again!',
      'download_link_not_found': 'Download link not found for this episode',
      'added_to_download': 'Added to download queue 📥',
      'download_all_started': 'Added %n% episodes to download queue',
      'download_all_failed': 'Could not add any episodes. Check your network!',
      'download_all_partial': 'Added %s%/%t% episodes. %f% failed',
      'downloading_all': 'Processing download all...',
      'no_internet_no_downloads': 'No Connection & No Downloads',
      'no_internet_msg':
          'Please check your internet connection to watch online or download movies for offline viewing.',
      'download_speed': 'Speed: %s%',
      'episodes_count': 'Episodes: %c%/%t%',
      'total_size': 'Size: %s% / %t%',
      'downloaded_movies': 'Downloaded Movies',
      'episode_count_label': '%n% episodes',
      'downloaded': 'Downloaded',
      'delete': 'Delete',
      'download_summary': 'Downloading %n% movies',
      'downloading_count': 'Downloading %n% movies',
      'episodes_completed': '%c%/%t% episodes downloaded',
      'all_downloaded': 'All downloaded',
      'download_eta': 'ETA: %e%',
      'movies': 'Movies',
      'no_history_msg': 'Movies you download will appear here',
      'delete_selected_movies_msg':
          'This action will delete selected episodes from your device.',
      'delete_all_episodes_msg':
          'This action will delete all episodes of this movie.',
      'local_playback_error':
          'Local playback error. File might be corrupted or missing data (HLS segments).',
      // Coach Mark
      'coach_menu_title': 'Main Menu',
      'coach_menu_desc':
          'Tap here to open the menu: language settings, permission check, and more options.',
      'coach_search_title': 'Search Movies',
      'coach_search_desc':
          'Tap here to search for movies, actors, or genres you love.',
      'coach_hero_title': 'Featured Movies',
      'coach_hero_desc':
          'Swipe to discover trending movies and personalized recommendations.',
      'coach_filter_title': 'Genre Filters',
      'coach_filter_desc':
          'Choose the movie genre you want: series, singles, anime, theaters...',
      'coach_movie_title': 'Movie List',
      'coach_movie_desc':
          'Tap any movie to view details, download, or add to favorites.',
      'coach_nav_title': 'Navigation Bar',
      'coach_nav_desc':
          'Navigate between Home, Search, Schedule, and Account here.',
      'got_it': 'Got it!',
      'next': 'Next',
      'coach_player_brightness_title': 'Screen Brightness',
      'coach_player_brightness_desc': 'Swipe up/down on the left half of the screen to adjust brightness.',
      'coach_player_volume_title': 'Volume Control',
      'coach_player_volume_desc': 'Swipe up/down on the right half of the screen to adjust volume.',
      'coach_player_seek_title': 'Double Tap to Seek',
      'coach_player_seek_desc': 'Double tap on the left/right half of the screen to rewind/fast-forward 10 seconds.',
      'comments': 'Comments',
      'write_comment': 'Write a comment...',
      'post': 'Post',
      'give_stars': 'Select rating stars (1-10)',
      'no_comments': 'No comments yet.',
      'register_website_msg': 'Please visit our website (https://dongmephim.online) to register a new account!',
      'rating_title': 'Rate Movie',
      'rating_submit': 'Submit Rating',
      'rating_success': 'Rating submitted successfully!',
      'rating_val_label': '%n%/10 rating',
      'unreleased_warning_title': 'Upcoming Episode ⏳',
      'unreleased_warning_body': 'This episode has not aired yet.\nAiring schedule: %time% - %date%',
      'unreleased_countdown': 'Airing in: %countdown%',
      'subscription_vip_title': 'DongMePhim VIP Privileges',
      'subscription_vip_desc': 'Watch UltraHD/4K movies with zero ads, ultra-fast VIP CDN server, unlock all blockbuster titles.',
      'upgrade_vip_btn': 'Upgrade now',
      'pkg_monthly': 'Monthly Plan',
      'pkg_annual': 'Annual Plan',
      'buy_package': 'Subscribe Plan',
      'payment_waiting': 'Waiting for payment...',
      'payment_instruction': 'Please scan the VietQR code below to pay via automatic SePay transfer.',
      'pay_confirm': 'Confirm Payment Transferred',
      'vip_server_locked_title': 'Restricted Server',
      'vip_server_locked_desc': 'Please upgrade your package to watch on this server!',
      'upgrade_now_btn': 'Upgrade Now',
      'billing_history': 'Billing History',
      'view_invoice_web': 'View Invoice (Web)',
      'promo_empty_msg': 'Please enter a promo code!',
      'promo_invalid_msg': 'Invalid promo code!',
      'promo_system_error': 'System error during promo code verification!',
      'promo_success_msg': 'Promo code applied successfully!',
      'payment_status_pending': 'Pending',
      'payment_status_approved': 'Approved',
      'payment_status_rejected': 'Rejected',
      'promo_applied_msg': 'Code "%code%" applied (%discount% off)',
      'compact_mode': 'Compact',
      'now_playing': 'Playing',
      'video_file_blocked': 'DongMePhim does not support opening local video files. Please search for movies directly in the app.',
      // Fallback compatibility keys for older client versions or fallback strings
      'Anime & Hoạt Hình': 'Anime & Animation',
      'Mới cập nhật': 'Newly Updated',
      'Phim Lẻ Hay Nhất': 'Best Singles',
      'Phim Bộ Đặc Sắc': 'Featured Series',
      'Xem nhiều nhất': 'Most Viewed',
      'TV Shows thực tế': 'Reality TV Shows',
      'Phim Chiếu Rạp Bom Tấn': 'Blockbuster Movies',
      'mark_read': 'Mark as read',
      'mark_all_read': 'Mark all as read',
      'clear_all': 'Clear all',
      'open_movie': 'Open movie',
      'current_episode': 'Current episode',
      'login_prompt_title': 'Login Required',
      'login_prompt_desc': 'You need to log in to view personalized movie update notifications from the system.',
      'login_now': 'Log in now',
      'login_required_watch_title': 'Login Required',
      'login_required_watch_desc': 'You need to log in to watch this movie.',
      'toast_marked_read': 'Marked as read',
      'toast_marked_all_read': 'Marked all notifications as read',
      'toast_cleared_all': 'Cleared all notifications',
      'no_schedule_found': 'No broadcast schedule available.',
      'no_movies_day': 'No movies scheduled for this day.',
      'request_movie': 'Request Movie',
      'film_name': 'Movie Title',
      'original_name': 'Original Title',
      'publish_year': 'Release Year',
      'link_phim': 'Movie Link (if any)',
      'author': 'Author/Director',
      'submit': 'Submit',
      'sending': 'Sending...',
      'request_success': 'Movie request submitted successfully!',
      'request_failed': 'Failed to submit request!',
      'enter_film_name': 'Please enter the movie title!',
      // Smart TV Keys
      'tv_unsupported_device': 'Samsung Smart TV devices are not officially supported yet.',
      'tv_registering_device': 'Registering TV device...',
      'tv_loading_config': 'Loading configuration info...',
      'tv_init_success': 'Initialization completed!',
      'tv_unsupported_title': 'Device Not Supported',
      'tv_samsung_block_msg': 'DongMePhim TV app currently does not support Samsung Tizen OS or Samsung emulators.\n\nPlease install and use the app on Android TV or Google TV.',
      'tv_exit_app': 'Exit Application',
      'tv_waiting_confirm': 'Waiting for confirmation...',
      'tv_qr_expired': 'QR Code has expired',
      'tv_refresh_qr': 'Refresh QR',
      'tv_login_success': 'TV login successful!',
      'tv_guest_mode_msg': 'You are viewing in Guest mode.',
      'tv_code_expired': 'Pairing code has expired!',
      'tv_get_new_code': 'Get new code',
      'tv_expired_after': 'Expires after: %time%',
      'tv_instructions': 'Instructions:',
      'tv_code_instruction_1': '1. Open DongMePhim app on Phone/Web.',
      'tv_code_instruction_2': '2. Go to Profile or Options Menu.',
      'tv_code_instruction_3': '3. Select "Login to TV" and enter the code above.',
      'tv_qr_instruction_1': '1. Open DongMePhim app on Phone.',
      'tv_qr_instruction_2': '2. Select TV QR code scanner function.',
      'tv_qr_instruction_3': '3. Scan the TV QR code and tap Confirm.',
      'tv_scan_qr_title': 'SCAN QR CODE TO CONNECT',
      'tv_code_login_title': 'LOGIN WITH TV CODE',
      'tv_skip_login': 'Skip, experience without login',
      'tv_menu_home': 'Home',
      'tv_menu_search': 'Search',
      'tv_menu_series': 'Series',
      'tv_menu_singles': 'Singles',
      'tv_menu_profile': 'Account',
      'tv_menu_logout': 'Sign Out',
      'tv_load_home_error': 'Failed to load TV homepage!',
      'tv_logout_confirm_title': 'Sign Out',
      'tv_logout_confirm_msg': 'Are you sure you want to sign out your account from this TV?',
      'tv_cancel': 'Cancel',
      'tv_logout': 'Sign Out',
      'tv_search_dev': 'Search is under development...',
      'tv_shelf_new': 'Newly Updated Movies',
      'tv_shelf_hot': 'Trending Movies',
      'tv_shelf_series': 'Featured Series',
      'tv_watch_now': 'Watch Now',
      'tv_info': 'Info',
      'tv_category_dev': 'Category lists are being updated...',
      'tv_logout_account': 'Sign Out Account',
      'tv_movie_not_found': 'Movie details not found!',
      'tv_server_error': 'Failed to connect to server!',
      'tv_back': 'Back',
      'tv_episodes_list': 'EPISODES LIST',
      'tv_no_episodes': 'No episodes available!',
      'tv_no_description': 'No description available for this movie.',
      'tv_dpad_guide': 'Use remote ◄ ▲ ▼ ► keys to navigate • Press OK to Select/Play',
      'tv_dpad_guide_title': 'TV Navigation Guide',
      'tv_dpad_guide_welcome': 'Welcome to DongMePhim Smart TV! Here is how to control the app using your Remote:',
      'tv_dpad_guide_arrows': 'Use the arrow keys ◄ ▲ ▼ ► (D-Pad) to navigate focus between movie items, lists, and menus.',
      'tv_dpad_guide_ok': 'Press the OK / Select button (Center of D-Pad) to open movies, play videos, or select actions.',
      'tv_dpad_guide_back': 'Press the BACK / ESC button on your remote to go back or close the player.',
      'tv_dpad_guide_hint': '💡 Hint: Select featured movies in the "Newly Updated" or "Trending" section to start watching!',
      'tv_select_season': 'SELECT OTHER SEASON',
      'select_season_hint': 'Select other season:',
      'tv_playing': 'Playing',
      'tv_paused': 'Paused',
      'tv_seek_forward': 'Fast forward +%seconds%s',
      'tv_seek_backward': 'Rewind -%seconds%s',
      'tv_player_loading': 'Loading high quality stream source...',
      // --- Ad overlay keys ---
      'ad_label': 'Advertisement',
      'ad_vip_hint': 'Sponsored Ad — Upgrade to VIP to disable',
      'ad_skip': 'Skip Ad',
      'ad_countdown': 'Skip in: %seconds%s',
      // --- Player UI keys ---
      'player_preparing': 'Preparing stream...',
      'player_locked': 'Screen locked!',
      'player_unlocked': 'Screen unlocked.',
      'player_error_stream': 'Error loading video stream!',
      'tv_hint_seek': 'Seek',
      'tv_hint_volume': 'Volume',
      'tv_hint_ok': 'Play/Pause',
      'tv_shelf_history': 'Watch History',
      'tv_shelf_favorites': 'Favorites',
      'tv_no_favorites': 'No favorite movies yet.',
      'tv_explore_now': 'Explore now',
      'tv_explore_hint': 'Explore exciting movies on the Home tab!',
      'tv_app_version': 'App Version',
      'tv_device_info': 'Device Info',
      // Log Viewer
      'log_sharing_prep': 'Preparing log file to share...',
      'log_cleared': 'All logs cleared!',
      'log_copied': 'Detailed logs copied!',
      'log_copy_failed': 'Copy failed: %error%',
      // Movie Details
      'no_stream_found': 'Streaming source not found!',
      'login_to_rate': 'Please log in to rate this movie!',
      'already_rated': 'You have already rated this movie!',
      'rating_submitting': 'Submitting rating...',
      'rating_failed': 'Rating failed. Please try again!',
      'comment_empty': 'Comment content cannot be empty.',
      'comment_success': 'Comment posted successfully!',
      'comment_failed': 'Failed to post comment. Try again later!',
      'reply_empty': 'Reply content cannot be empty.',
      'reply_submitting': 'Submitting reply...',
      'reply_success': 'Reply posted successfully!',
      'reply_failed': 'Failed to post reply. Try again later!',
      'comment_liked': 'Liked comment ❤️',
      'comment_deleted': 'Comment deleted.',
      'comment_delete_title': 'Delete comment?',
      'comment_delete_confirm': 'Are you sure you want to delete this comment?',
      'login_to_comment': 'Please log in to comment on this movie!',
      // Profile & VIP
      'vip_remaining': 'Remaining',
      'vip_expiry_date': 'Until',
      'vip_privileges': 'Privileges',
      'billing_monthly_tab': 'Monthly Plan',
      'billing_annual_tab': 'Annual Plan',
      'billing_cycle_title': 'Select Billing Cycle',
      'payment_method_title': 'Payment Method',
      'sepay_gateway_title': 'Automatic SePay Gateway',
      'sepay_gateway_desc': 'Scan banking QR code to get package instantly.',
      'manual_vietqr_title': 'Manual VietQR Bank Transfer',
      'manual_vietqr_desc': 'Transfer manually and confirm for system check.',
      'promo_code_title': 'Promo Code',
      'total_title': 'Total',
      'price_includes_vat': 'Price includes VAT',
      'discount_label': 'Discount',
      'renew_action': 'Renew %pkg% now',
      'upgrade_action': 'Upgrade to %pkg% now',
      'history_cleared': 'Watch history cleared',
      'history_clear_failed': 'Failed to clear history. Please try again!',
      'loading_vip_info': 'Loading package info...',
      'history_clear_confirm': 'Are you sure you want to delete all watch history?',
      'upgrade_vip_title': 'Upgrade Account',
      'vietqr_scan_title': 'Scan VietQR Code to transfer',
      'vietqr_scan_desc': 'The system automatically approves the package after receiving the transfer with the correct note.',
      'bank_label': 'Bank:',
      'account_no_label': 'Account No:',
      'account_name_label': 'Account Owner:',
      'amount_label': 'Amount:',
      'transfer_note_label': 'Transfer Note:',
      'open_sepay_pg_web': 'Open SePay Payment Gateway (Web)',
      'no_account_yet': 'Don\'t have an account? ',
      'register_now': 'Register now',
      'vip_card_desc_active': 'High quality playback privileges',
      'vip_card_desc_inactive': 'Subscribe to unlock copyrighted content',
      'renew_btn': 'Renew',
      'upgrade_btn': 'Upgrade',
      'choose': 'Choose',
      'watch_history': 'Watch History',
      'favorites_list': 'My Favorites',
      'status_pending': 'Pending',
      'status_approved': 'Approved',
      'status_rejected': 'Rejected',
      'tv_link_title': 'Smart TV Connection',
      'tv_scan_qr_title_btn': 'Scan Smart TV QR Code',
      'tv_scan_qr_desc_btn': 'Scan the QR code displayed on TV to connect quickly',
      'creating_tx': 'Creating transaction...',
      'payment_pending_msg': 'Payment request pending review! Please reload page in 1-2 minutes.',
      'payment_open_failed': 'Could not open payment gateway. Please scan QR to transfer.',
      'confirm_transferred': 'Confirm transferred',
      'no_favorites_yet': 'No favorite movies yet.',
      'tv_login_by_code': 'Login to TV using code',
      'tv_login_enter_code': 'Enter the 8-character code shown on your TV',
      // QR Scan
      'qr_invalid': 'Invalid QR code!',
      'qr_read_error': 'Error reading QR: %error%',
      'login_on_phone_first': 'Please log in on your phone first!',
      'qr_scan_failed': 'QR scan failed!',
      'qr_expired': 'QR code invalid or expired!',
      'server_conn_error': 'Server connection error: %error%',
      // TV Pairing & Link Confirm
      'pairing_success': 'Device paired successfully!',
      'pairing_confirm_error': 'Link confirmation error!',
      'conn_error': 'Connection error: %error%',
      'pairing_rejected': 'TV pairing request rejected!',
      'agree_login_tv': 'Agree & Login TV',
      'tv_paired_success': 'TV device paired successfully!',
      'confirm_btn': 'Confirm',
      'tv_pair_code_invalid': 'Please enter all 4 digits!',
      'tv_pair_code_incorrect': 'Incorrect TV pairing code!',
      'tv_pair_code_expired_msg': 'TV pairing code invalid or expired!',
      'server_conn_error_retry': 'Server connection error. Please try again!',
      'tv_login_title_modal': 'Log In to TV',
      'tv_login_enter_code_desc': 'Enter the code shown on your Smart TV to quickly connect your account:',
      'cancel_btn': 'Cancel',
      'tv_confirm_login_title': 'Confirm TV Login',
      'tv_confirm_login_desc': 'Do you want to log in to your account on this TV device?',
      'tv_device_info_title': 'TV DEVICE INFO',
      'tv_device_name_label': 'Device Name:',
      'tv_device_os_label': 'OS:',
      'tv_device_model_label': 'Model:',
      'tv_device_ip_label': 'IP Address:',
      'tv_device_location_label': 'Location:',
      'tv_device_isp_label': 'ISP:',
      'reject_btn': 'Reject',
      // TV Player Screen
      'tv_no_stream_found': 'Streaming source not found for this episode!',
      'tv_conn_error': 'Server connection error!',
      // TV Profile Tab
      'switched_to_vi': 'Switched to Vietnamese',
      'switched_to_en': 'Switched to English',
      'exit_tv_emulator': 'Exited TV emulator mode',
      // Video Player & Ads
      'server_no_stream': 'Streaming stream not found on this server!',
      'ep_not_updated_on_server': 'Current episode not updated on this server yet!',
      'intro_skipped': 'Intro skipped',
      'outro_skipped': 'Outro skipped',
      'player_no_stream': 'Streaming source not found for this episode!',
      'play_speed_toast': 'Play speed: %speed%x',
      'ad_error_skip': 'Ad error - Skipping',
      'ad_load_failed': 'Could not load video advertisement from system.',
      'ad_loading_yt': 'Playing YouTube ad...',
      'sponsored_link': 'Sponsored link',
      'next_video_countdown': 'Next video in %seconds%',
      'playlist_drawer_title': 'PLAYLIST',
      // API Services
      'sync_success': 'Data synchronized successfully!',
      'sync_unexpected_error': 'Connection error or unexpected error: %error%',
      'skip_outro': 'Skip Outro',
      'subtitle_settings': 'Subtitle Settings',
      'play_now': 'Play Now',
      'rate_label': 'Rate',
      'anonymous': 'Anonymous',
      'api_url_label': 'API PATH (URL)',
      'sub_mode_off': 'Off',
      'sub_mode_primary': 'Single',
      'sub_mode_bilingual': 'Bilingual',
      'sub_mode_label': 'Subtitle mode: %mode%',
      'select_primary_sub': '--- SELECT PRIMARY SUBTITLE ---',
      'select_secondary_sub': '--- SELECT SECONDARY SUBTITLE ---',
      'currently_selected': ' (Selected)',
      'select_speed': '--- SELECT PLAYBACK SPEED ---',
      'speed_normal': 'Normal',
      'switch_episode': '--- SWITCH EPISODE ---',
      'prev_episode_label': 'Previous: %name%',
      'next_episode_label': 'Next: %name%',
      'tv_select_server_section': '--- SELECT SOURCE (SERVER) ---',
      'episode_list_playlist': 'Episode List (Playlist)',
      'episode_list': 'Episode List',
      'play_speed': 'Playback Speed',
      'server': 'Server',
      'default_server': 'Default Server',
      'close_settings': 'Close settings',
      'sub_style_title': 'SUBTITLE STYLING',
      'sub_font_size': 'SUBTITLE FONT SIZE',
      'sub_color': 'SUBTITLE TEXT COLOR',
      'sub_border': 'SUBTITLE BORDER STYLE',
      'sub_opacity': 'SUBTITLE BACKGROUND OPACITY',
      'sub_pos': 'BILINGUAL SUBTITLE POSITION',
      'sub_color_white': 'White',
      'sub_color_yellow': 'Yellow',
      'sub_color_green': 'Green',
      'sub_color_blue': 'Blue',
      'sub_border_shadow': 'Shadow',
      'sub_border_stroke': 'Stroke',
      'sub_border_none': 'None',
      'sub_pos_top': 'Top',
      'sub_pos_bottom': 'Bottom',
      'primary_sub_label': 'Primary subtitle',
      'secondary_sub_label': 'Secondary subtitle',
      'playback_speed': 'Playback speed',
      'sub_on': 'On',
      'date_prefix': 'on',
      'episode_prefix': 'Episode',
      'next_episode_fallback': 'Next Episode',
      'broadcast_single_full': 'The full HD movie will be broadcasted %time%',
      'broadcast_single_standard': 'The movie will be broadcasted %time%',
      'broadcast_series_full': 'The full series will be broadcasted %time%',
      'broadcast_series_final': 'The final episode will be broadcasted %time%',
      'broadcast_series_standard': '%episode% will be broadcasted %time%',
      'countdown_days': 'd',
      'countdown_hours': 'h',
      'countdown_minutes': 'm',
      'countdown_seconds': 's',
      'countdown_unreleased': 'Unreleased',
      'broadcast_countdown_label': 'Broadcasting in',
      // Subscription & Coupon
      'renew_same_pkg_title': 'Renew Package',
      'renew_same_pkg_desc': 'You are on %pkg%. Renewal will extend your current expiry date.',
      'switch_pkg_title': 'Switch Package',
      'switch_pkg_desc': 'You are on %current%. Switching to %new% will reset your subscription from today. Continue?',
      'upgrade_from_free_title': 'Upgrade to VIP',
      'upgrade_from_free_desc': 'Choose a billing cycle to start enjoying VIP privileges.',
      'billing_monthly': 'Monthly',
      'billing_annual': 'Annual',
      'savings_amount': 'Save %amount%',
      'coupon_input_hint': 'Enter promo code',
      'coupon_apply_btn': 'Apply',
      'coupon_applied_label': 'Code applied',
      'coupon_expiry_label': 'Expires: %date%',
      'coupon_savings_label': 'Savings',
      'original_price_label': 'Original price',
      'discounted_price_label': 'Discounted price',
      'open_checkout_web': 'Open checkout page (Web)',
    },
  };

  static String get currentLang => _currentLang;

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString('txa_lang');
    if (saved != null) {
      _currentLang = saved;
    } else {
      // Automatic detection
      try {
        final locale = Platform.localeName.split('_')[0];
        if (_dicts.containsKey(locale)) {
          _currentLang = locale;
        } else {
          _currentLang = 'en'; // Default
        }
      } catch (_) {
        _currentLang = 'vi';
      }
    }
  }

  static Future<void> setLang(String lang) async {
    if (_dicts.containsKey(lang)) {
      _currentLang = lang;
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('txa_lang', lang);
      _instance.notifyListeners();
      onLanguageChanged?.call();
    }
  }

  static String t(String key, {Map<String, String>? replace}) {
    if (_dicts[_currentLang]?[key] == null) {
      TxaLogger.log("Missing translation key '$key' for language '$_currentLang'", type: 'app');
    }
    String text = _dicts[_currentLang]?[key] ?? _dicts['en']?[key] ?? key;
    if (replace != null) {
      replace.forEach((k, v) {
        text = text.replaceAll('%$k%', v);
      });
    }
    return text;
  }
}
